example/package-lock.json, example/package.json, example/src/components/BusinessBasicInformation/index.tsx, example/src/components/BusinessBasicInformation/styles.tsx, example/src/components/BusinessInformation/index.tsx, example/src/components/BusinessInformation/styles.tsx, example/src/components/BusinessProductsListing/index.tsx, example/src/components/BusinessReviews/index.tsx, example/src/components/BusinessReviews/styles.tsx, example/src/components/BusinessesListing/index.tsx, example/src/components/BusinessesListing/styles.tsx, example/src/components/Messages/index.tsx, example/src/components/MomentOption/index.tsx, example/src/components/MomentOption/styles.tsx, example/src/components/OrderDetails/index.tsx, example/src/components/OrderMap.tsx, example/src/components/OrderTypeSelector/index.tsx, example/src/components/OrderTypeSelector/styles.tsx, example/src/components/shared/ODropDown.tsx, example/src/components/shared/OModal.tsx, example/src/navigators/HomeNavigator.tsx, example/src/navigators/RootNavigator.tsx, example/src/pages/MomentOption.tsx, example/src/types/index.tsx
DeliveryTime and OrderTypeSelector
=> Deliery time and order type

example/src/components/BusinessBasicInformation/index.tsx, example/src/components/NavBar.tsx, example/src/layouts/SafeAreaContainer.tsx, example/src/navigators/BottomNavigator.tsx, example/src/pages/Home.tsx, example/src/pages/MyOrders.tsx, example/src/pages/OrderDetails.tsx, example/src/pages/Profile.tsx
[Add] font list to solve the compile error in iOS
=> some fix and Improvement for ios

example/src/components/AddressList/index.tsx, example/src/components/BusinessProductsListing/index.tsx, example/src/components/Cart/index.tsx, example/src/components/UpsellingProducts/index.tsx, example/src/types/index.tsx
=> Implement upselling

example/src/components/Cart/index.tsx, example/src/components/OrderSummary/index.tsx, example/src/components/OrderSummary/styles.tsx, example/src/components/ProductForm/index.tsx, example/src/components/ProductItemAccordion/index.tsx, example/src/components/ProductItemAccordion/styles.tsx, example/src/types/index.tsx
=> [ADD] edit and delete actions for productAccordion

example/src/components/BusinessProductsListing/index.tsx, example/src/components/Cart/index.tsx, example/src/components/Checkout/index.tsx, example/src/components/CouponControl/index.tsx, example/src/components/OrderSummary/index.tsx, example/src/components/UpsellingProducts/index.tsx, example/src/components/shared/OBottomPopup.tsx
=> [FIX] some bugs and styles

example/src/components/OrdersOption/index.tsx, example/src/components/PreviousOrders/index.tsx, example/src/components/PreviousOrders/styles.tsx, example/src/types/index.tsx
=> [ADD] load more orders for previous orders, Reorder and fix card styles

example/src/components/Checkout/index.tsx, example/src/components/PhoneInputNumber/index.tsx, example/src/components/UserDetails/index.tsx, example/src/components/UserFormDetails/index.tsx, example/src/components/UserFormDetails/styles.tsx, example/src/components/UserProfileForm/index.tsx, example/src/components/UserProfileForm/styles.tsx, example/src/types/index.tsx
=> Phone number for profile and checkout

example/src/components/Checkout/styles.tsx, example/src/components/Home/index.tsx, example/src/components/OrderTypeSelector/index.tsx, example/src/components/UserProfileForm/index.tsx, example/src/components/shared/ODropDown.tsx, example/src/theme.tsx
=> Fix and bugs 19/04

example/src/components/BusinessProductsList/index.tsx, example/src/components/BusinessProductsListing/index.tsx, example/src/components/BusinessProductsListing/styles.tsx, example/src/components/NotFoundSource/index.tsx, example/src/components/NotFoundSource/styles.tsx, example/src/types/index.tsx
Story: https://app.asana.com/0/1191220738645130/1200218512138704
Empty cart button deleted, hide button when business has not products
Demo: https://d.pr/v/Dusg9b
=> [FIX] show of the notFoundError in businessProducts

example/src/components/AddressForm/index.tsx, example/src/components/AddressList/index.tsx, example/src/pages/AddressForm.tsx, example/src/types/index.tsx
Error when sign up and add a new address, then redirect to bottomTab
Demo: https://d.pr/v/D4YRYd
=> [FIX] redirect for user without addressesList

example/src/components/AddressForm/index.tsx, example/src/components/ForgotPasswordForm/index.tsx, example/src/components/LoginForm/index.tsx, example/src/components/OrderDetails/index.tsx, example/src/components/PaymentOptions/index.tsx, example/src/components/SignupForm/index.tsx, example/src/components/UserFormDetails/index.tsx, example/src/components/UserProfileForm/index.tsx, example/src/components/shared/OInput.tsx, example/src/components/shared/OToast.tsx, example/src/pages/Checkout.tsx
Demo: https://d.pr/v/1bZ3M7, https://d.pr/v/vJ9Ss2
=> Login/signup and some fixes 

example/src/components/AddressForm/index.tsx, example/src/components/AddressForm/styles.tsx, example/src/pages/AddressForm.tsx
=> [FIX] default autocorrect for addressInput and input styles

example/src/components/ForgotPasswordForm/index.tsx, example/src/components/LoginForm/index.tsx, example/src/components/SignupForm/index.tsx, example/src/components/UserFormDetails/index.tsx, example/src/components/UserProfileForm/index.tsx, example/src/types/ordering-api-sdk/index.d.ts, example/tsconfig.json
The email input no longer allows the following characters: &,()%";:ç?<>{}[]
=> Email input char

example/src/components/AddressForm/index.tsx, example/src/components/OrdersOption/index.tsx
Demo Android https://d.pr/i/LSOxi0
=> [FIX] zIndex of dropdown autocomplete

example/src/components/AddressList/index.tsx, example/src/navigators/HomeNavigator.tsx
Story: https://app.asana.com/0/1191220738645130/1200190732342737, https://app.asana.com/0/1191220738645130/1200286893552987
Demo: https://d.pr/v/sIgXOq, https://d.pr/v/M15vGz
=> [add] splash for login

example/src/components/AddressList/index.tsx, example/src/components/Checkout/index.tsx, example/src/components/OrderSummary/index.tsx, example/src/components/ProductForm/index.tsx, example/src/components/ProductItemAccordion/index.tsx, example/src/navigators/CheckoutNavigator.tsx, example/src/navigators/HomeNavigator.tsx, example/src/pages/AddressList.tsx
Story: https://app.asana.com/0/1191220738645130/1200286893552993
=> Checkout spinners

example/src/components/MomentOption/index.tsx
=> [FIX] freeze app when change moment

example/src/components/BusinessProductsCategories/index.tsx, example/src/components/SearchBar/index.tsx, example/src/components/shared/OInput.tsx
=> [ADD] returnkeybutton for searchBar

example/src/components/BusinessTypeFilter/index.tsx, example/src/components/BusinessTypeFilter/styles.tsx, example/src/components/BusinessesListing/index.tsx, example/src/components/Cart/index.tsx, example/src/components/Checkout/index.tsx, example/src/components/DriverTips/index.tsx, example/src/components/DriverTips/styles.tsx, example/src/components/OrderDetails/index.tsx, example/src/components/OrderSummary/index.tsx, example/src/pages/Checkout.tsx, example/src/types/index.tsx, example/src/utils/index.tsx
=> Improves some changes

example/src/components/PhoneInputNumber/index.tsx, example/src/components/UserFormDetails/index.tsx, example/src/components/UserProfileForm/index.tsx, example/src/types/index.tsx, example/src/utils/index.tsx
Story: https://app.asana.com/0/1191220738645130/1200286893552988
=> [FIX] default country code of userEdits

example/package.json
The error was ocurred in some native activities
=> Updating stripe version

example/src/components/ActiveOrders/index.tsx, example/src/components/BusinessBasicInformation/index.tsx, example/src/components/BusinessController/index.tsx, example/src/components/BusinessProductsListing/index.tsx, example/src/components/Checkout/styles.tsx, example/src/components/OrdersOption/index.tsx, example/src/components/PreviousOrders/index.tsx, example/src/components/ProductForm/index.tsx, example/src/components/ProductForm/styles.tsx, example/src/components/ProductOptionSubOption/index.tsx, example/src/components/shared/OModal.tsx, example/src/config.json
=> React issues 11 june

example/src/components/BusinessController/index.tsx
=> [FIX] close timing

example/src/components/ProductItemAccordion/index.tsx
=> [FIX] no ingredients bug on orderDetails

example/src/components/ActiveOrders/index.tsx, example/src/components/OrdersOption/index.tsx, example/src/components/OrdersOption/styles.tsx, example/src/types/index.tsx
=> [ADD] preorders block for myorders, [FIX] load more orders position

example/package.json, example/yarn.lock
Added the missing Deps in `yarn.lock` and `package.json` react-native-app-intro-slider
=> Added the missing Deps react-native-app-intro-slider

example/src/components/BusinessProductsListing/index.tsx, example/src/components/BusinessesListing/index.tsx, example/src/types/index.tsx
=> Product list pagination

example/src/components/PhoneInputNumber/index.tsx
Add button "update" when user has no phone number
Video: https://d.pr/v/lO0TUh
=> Add button update when no phone

example/src/components/ProductOptionSubOption/index.tsx, example/src/components/ProductOptionSubOption/styles.tsx
=> [FIX] alignment of product options

example/src/components/LogoutButton/index.tsx
LocalStorage Improvement for introductory page
=> LocalStorage Improvement for introductory page

example/src/components/BusinessController/index.tsx
=> [FIX] text closed position

example/src/pages/IntroductoryTutorial.tsx
iPhone 8, iPhone 11 Pro Max, iPhone 12 mini
- https://d.pr/i/kRn2TA
iPhone SE (2nd generation)
- https://d.pr/i/8ZJ5Pc
iPhone 12 Pro Max
- https://d.pr/i/2NjDE8
iPhone 12
- https://d.pr/i/BxxfDV
iPad Pro (9.7-inch)
- https://d.pr/i/UTEPNw
=> fix-introductory-page-compatibility

example/src/themes/business/src/components/OrderDetails/index.tsx, example/src/themes/business/src/components/PhoneInputNumber/index.tsx, example/src/themes/business/src/components/UserFormDetails/index.tsx, example/src/themes/business/src/components/UserFormDetails/styles.tsx, example/src/themes/business/src/components/UserProfileForm/index.tsx, example/src/themes/business/src/components/UserProfileForm/styles.tsx, example/src/themes/business/src/types/index.tsx
descriptions:
fixed bugs in ordersDetails and Profile components
=> fix: fixed bugs in ordersDetails and Profile components

example/themes/business/src/components/BusinessController/index.tsx, example/themes/business/src/components/Chat/index.tsx, example/themes/business/src/components/Home/index.tsx, example/themes/business/src/components/LoginForm/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PhoneInputNumber/index.tsx, example/themes/business/src/components/PreviousOrders/index.tsx, example/themes/business/src/components/SearchBar/index.tsx, example/themes/business/src/components/SignupForm/index.tsx, example/themes/business/src/components/StoresList/index.tsx, example/themes/business/src/components/UserFormDetails/index.tsx, example/themes/business/src/components/UserProfileForm/index.tsx, example/themes/business/src/components/shared/OInput.tsx
It needs this other change to work:
https://github.com/Ordering-Inc/ordering-components/pull/446
=> Fix: improved load of orders and stores

example/themes/business/src/components/Chat/index.tsx, example/themes/business/src/components/Chat/styles.tsx, example/themes/business/src/components/LanguageSelector/index.tsx, example/themes/business/src/components/LanguageSelector/lang_country.json, example/themes/business/src/components/LanguageSelector/styles.tsx, example/themes/business/src/components/OrderDetails/styles.tsx, example/themes/business/src/components/OrderMessage/index.tsx, example/themes/business/src/components/PreviousMessages/index.tsx, example/themes/business/src/components/StoresList/index.tsx, example/themes/business/src/components/shared/OToast.tsx, example/themes/business/src/types/index.tsx, example/themes/business/src/utils/index.tsx
Require this change:
https://github.com/Ordering-Inc/ordering-components/pull/447
=> Feat: implemented filter chat

example/themes/doordash/src/components/ActiveOrders/index.tsx, example/themes/doordash/src/components/AddressForm/index.tsx, example/themes/doordash/src/components/AddressList/index.tsx, example/themes/doordash/src/components/BusinessProductsListing/index.tsx, example/themes/doordash/src/components/BusinessesListing/index.tsx, example/themes/doordash/src/components/Checkout/index.tsx, example/themes/doordash/src/components/Checkout/styles.tsx, example/themes/doordash/src/components/ForgotPasswordForm/index.tsx, example/themes/doordash/src/components/Home/index.tsx, example/themes/doordash/src/components/LoginForm/index.tsx, example/themes/doordash/src/components/LogoutButton/index.tsx, example/themes/doordash/src/components/Messages/index.tsx, example/themes/doordash/src/components/OrderDetails/index.tsx, example/themes/doordash/src/components/OrdersOption/index.tsx, example/themes/doordash/src/components/PaymentOptions/index.tsx, example/themes/doordash/src/components/ProductForm/index.tsx, example/themes/doordash/src/components/ReviewOrder/index.tsx, example/themes/doordash/src/components/SignupForm/index.tsx, example/themes/doordash/src/components/StripeRedirectForm/index.tsx, example/themes/doordash/src/components/UserFormDetails/index.tsx, example/themes/doordash/src/components/UserProfileForm/index.tsx, example/themes/doordash/src/components/shared/OButton.tsx, example/themes/doordash/src/components/shared/ODropDown.tsx, example/themes/doordash/src/components/shared/OIcon.tsx, example/themes/doordash/src/components/shared/OInput.tsx, example/themes/doordash/src/layouts/Container.tsx, example/themes/doordash/src/layouts/SafeAreaContainer.tsx, example/themes/doordash/src/providers/AlertProvider.tsx, example/themes/doordash/src/utils/index.tsx
fixed issues and updated theme structure
=> doordash template in order to update ordering-ui-react-native package

example/src/components/BusinessInformation/index.tsx, example/src/components/BusinessInformation/styles.tsx
=> Show text close if schedule disabled

example/themes/business/src/components/BusinessController/index.tsx, example/themes/business/src/components/OrderDetails/index.tsx, example/themes/business/src/components/OrderDetails/styles.tsx, example/themes/business/src/components/OrderSummary/index.tsx, example/themes/business/src/components/StoresList/index.tsx
its necessary merge pr on ordering api sdk and ordering component
=> fix bugs in components and update loaders

example/themes/business/src/components/MessagesOption/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousMessages/index.tsx, example/themes/business/src/types/index.tsx
This update requiere:
https://github.com/Ordering-Inc/ordering-components/pull/457
=> Fix: improvements in pagination and socket in messages view

example/themes/kiosk/src/components/Cart/index.tsx, example/themes/kiosk/src/components/LanguageSelector/index.tsx, example/themes/kiosk/src/components/LoginForm/index.tsx, example/themes/kiosk/src/components/OrderDetails/index.tsx, example/themes/kiosk/src/components/OrderTypeSelector/index.tsx, example/themes/kiosk/src/components/shared/OInput.tsx
Story: https://app.asana.com/0/1191220738645130/1200900003812341
=> add kiosk improves

example/themes/business/src/components/Chat/index.tsx, example/themes/business/src/components/MessagesOption/index.tsx, example/themes/business/src/components/PreviousMessages/index.tsx, example/themes/business/src/types/index.tsx
This change require:
https://github.com/Ordering-Inc/ordering-components/pull/461
=> Feat: added orders socket in messages view

example/themes/doordash/src/components/AddressForm/index.tsx
Get current location for Template 2
=> Template 2 Address form

example/themes/uber-eats/src/components/AddressForm/index.tsx, example/themes/uber-eats/src/components/AddressList/index.tsx, example/themes/uber-eats/src/components/BusinessesListing/index.tsx, example/themes/uber-eats/src/components/Cart/index.tsx, example/themes/uber-eats/src/components/Home/index.tsx, example/themes/uber-eats/src/components/LanguageSelector/index.tsx, example/themes/uber-eats/src/components/LanguageSelector/styles.tsx, example/themes/uber-eats/src/components/SignupForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1200909834342628
=> Improvements and fix bugs

example/themes/uber-eats/src/components/AddressForm/index.tsx
=> Template 3 Address Form

example/themes/instacart/src/components/AddressForm/index.tsx, example/themes/instacart/src/components/shared/OIcon.tsx
=> Template 4 Address Form

example/src/components/Checkout/index.tsx, example/src/navigators/HomeNavigator.tsx
=> [fix] other errors and url paypal

example/themes/business/src/components/MessagesOption/index.tsx, example/themes/business/src/components/OrderDetailsDelivery/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/UserProfileForm/index.tsx, example/themes/business/src/types/index.tsx
This improve has a bug with the profile view. When the user's information updated the loadOrder funtion is called so the order pagination increase.
=> remove useFocusEffect and increase order limit

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousOrders/index.tsx
story: https://app.asana.com/0/inbox/1200505565811864/1201041808074205/1201041811822639 , add function sort
=> add sort function

example/src/index.tsx
=> Export HelpParams

example/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201067419700385/f
Video: https://d.pr/v/Gmxokp
=> [FIX] Subtotal amount when tax included in price.

example/package.json, example/src/components/OrderDetails/index.tsx, example/src/components/SignupForm/index.tsx, example/themes/doordash/src/components/SignupForm/index.tsx, example/themes/instacart/src/components/SignupForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/uber-eats/src/components/SignupForm/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201069818336849
=> [Feat] add the Terms & Conditions and [Fix] review orders

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousOrders/index.tsx, example/themes/business/src/types/index.tsx
This changed require: https://github.com/Ordering-Inc/ordering-components/pull/505
=> Feat: implemented pagination and orders independent

example/src/components/BusinessesListing/index.tsx, example/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1200517202404523/1201050810896962/f
=> Disable Moment if config disabled.

example/package.json, example/src/components/OrderDetails/index.tsx, example/src/components/OrderDetails/styles.tsx, example/src/pages/OrderDetails.tsx, example/src/types/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1188675693896486/1201067085370922
DEMO: https://d.pr/v/FRkY5C
=> Add loading and error validation for order details

example/src/components/PreviousOrders/index.tsx, example/src/components/ReviewOrder/index.tsx, example/src/pages/ReviewOrder.tsx, example/src/types/index.tsx, example/yarn.lock
Review button don't show for orders already reviewed.
STORY: https://app.asana.com/0/1198717964402573/1201112191266302
=> [Fix] bug in MyOrders

example/src/components/ProductOptionSubOption/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201146527706369/f
Video: https://d.pr/v/JYCUkN
=> [FIX] Suboption quantity validation

example/ios/Podfile.lock, example/themes/doordash/src/components/SignupForm/index.tsx, example/themes/instacart/src/components/SignupForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201196441543312
=> [Feat] Terms condition in the template instcart, doordash, orignal

example/src/components/BusinessReviews/index.tsx
Story: https://app.asana.com/0/0/1201296386967276/f
iOS: https://d.pr/i/eHxy8d
Android: https://d.pr/i/fP89UP
=> [FIX] Text alignment in review comment section

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/OrdersOption/styles.tsx
Story: https://app.asana.com/0/0/1201304580358193/f
Video: https://d.pr/v/2VmA1o
=> [FIX] Orders now are displayed correctly

example/themes/original/src/components/UserProfile/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1201308237107204
=> Change icon name in template 5

example/src/components/SignupForm/index.tsx
Story: https://app.asana.com/0/0/1201304580358202/f
Video: https://d.pr/v/AAnKyE
=> [FIX] text is now shown completly

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/0/1201315143822109/f
=> Only show text for business app

example/themes/business/src/components/OrderDetails/Delivery.tsx
Story: https://app.asana.com/0/0/1201320258106969/f
Image: https://d.pr/i/LwhvmM
=> change language variable

example/src/components/PaymentOptions/index.tsx
Story: https://app.asana.com/0/1201115702325003/1201322808602001/f
=> [FIX] Exclude by gateway

example/themes/business/src/components/NewOrderNotification/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201324857294296
Demo: https://d.pr/v/sUolUZ?showPanel=1
=> [Fix] feedback for delivery app

example/ios/Podfile.lock, example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1201282679145208
Demo: https://d.pr/v/JKv3tS
=> [FIX] feedback for original app

example/src/components/BusinessProductsListing/index.tsx, example/src/components/Cart/index.tsx, example/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201318934759914/f
Video: https://d.pr/v/945Jly
=> [FIX] minimum purchase when tax included in price

example/src/components/AddressForm/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201333851191061/f
Video: https://d.pr/v/yL5znd
=> [FIX] if config disabled don't show field

example/src/components/MomentOption/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201333851191073/f
Video: https://d.pr/v/WUYu0y
=> [FIX] Time selected

example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/components/shared/OInput.tsx, example/themes/original/src/layouts/Container.tsx
STORY: https://app.asana.com/0/1198717964402573/1201314427666798
=> Fix the feedback for the original app

example/src/components/OrderCreating/index.tsx
Story: https://app.asana.com/0/1201115702325003/1201386140912117/f
=> [FIX] validate if value null

example/themes/kiosk/src/components/BusinessProductsListing/index.tsx, example/themes/kiosk/src/components/CategoriesMenu/index.tsx
Story:
https://app.asana.com/0/0/1201314427666757/f
https://app.asana.com/0/0/1201314427666763/f
Video: https://d.pr/v/27IKY0
=> [FIX] scroll in featured categories and change category name

example/themes/kiosk/src/components/NavBar/index.tsx, example/themes/kiosk/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/0/1201314427666760/f
video: https://d.pr/v/mzBUQC
=> [FIX] design in product form

example/themes/kiosk/src/components/CartBottomSheet/index.tsx, example/themes/kiosk/src/components/CartItem/index.tsx, example/themes/kiosk/src/components/shared/OIconButton.tsx
Story:
https://app.asana.com/0/0/1201314427666786/f
https://app.asana.com/0/0/1201314427666767/f
https://app.asana.com/0/0/1201314427666765/f
=> [FIX] Design in Cart component

example/themes/kiosk/src/components/CategoriesMenu/index.tsx
Story: https://app.asana.com/0/0/1201314427666785/f
=> [FIX] Product design when side menu enabled

example/themes/kiosk/src/components/UpsellingProducts/index.tsx
Story: https://app.asana.com/0/0/1201314427666782/f
=> Change up-selling design

example/themes/kiosk/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/0/1200526498353222/f
=> Add 1 min timer after order confirmation to redirect to home

example/themes/kiosk/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/0/1201314427666777/f
=> Add close icon in nav bar-orderdetials

example/themes/kiosk/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/0/1201314427666780/f
=> change design

example/themes/kiosk/src/components/CustomerName/index.tsx
Story:
https://app.asana.com/0/0/1201314427666775/f
https://app.asana.com/0/0/1201314427666774/f
Image: https://d.pr/i/rdCJQu
=> add skip button in customerName component

example/themes/kiosk/src/components/CustomerName/index.tsx
Story: https://app.asana.com/0/0/1201314427666776/f
=> [FIX] When customer click enter

example/themes/kiosk/src/components/BusinessMenu/index.tsx, example/themes/kiosk/src/components/BusinessProductsListing/index.tsx, example/themes/kiosk/src/components/CartBottomSheet/index.tsx, example/themes/kiosk/src/components/CartContent/index.tsx, example/themes/kiosk/src/components/CategoriesMenu/index.tsx, example/themes/kiosk/src/components/UpsellingProducts/index.tsx, example/themes/kiosk/src/types/index.d.ts
Story: https://app.asana.com/0/0/1200526498353223/f
Video: https://d.pr/v/ZwVOP9
=> [ADD] inactivity user after 2min

example/themes/kiosk/src/components/BusinessMenu/index.tsx
=> 2min inactivity

example/themes/instacart/src/components/BusinessProductsList/index.tsx, example/themes/instacart/src/components/BusinessProductsListing/index.tsx, example/themes/instacart/src/components/SingleProductCard/index.tsx, example/themes/instacart/src/components/SingleProductCard/styles.tsx, example/themes/instacart/src/types/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201439350138202
=> [Fix] feedback for the template instacart

example/src/components/BusinessBasicInformation/index.tsx, example/src/components/PreviousOrders/index.tsx, example/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201374781348682/f
https://d.pr/v/C5BWD7
https://slack-files.com/T0D4MPDCY-F02Q9942R7B-721861c0fe
https://d.pr/v/ewyYxS
=> [FIX] Add scroll view

example/themes/kiosk/src/components/BusinessProductsListing/index.tsx, example/themes/kiosk/src/components/CategoriesMenu/index.tsx, example/themes/kiosk/src/components/NavBar/index.tsx, example/themes/kiosk/src/components/OrderDetails/index.tsx, example/themes/kiosk/src/components/UpsellingProducts/index.tsx
https://app.asana.com/0/1201115702325003/1200526498353220/f
=> [FIX] design for iPad devices

example/src/components/Account/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201514599298113/f
=> [FIX] image change in account component

example/src/components/GoogleMap/index.tsx, example/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201447254620457/f
Video: https://d.pr/v/1a5HBW
=> [FIX] update driver location on map

example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/OrderProgress/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201187668366381
=> Order progress update

example/src/components/AddressList/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201501544225799/f
Video: https://d.pr/v/M7oO2j
=> [FIX] no permission message

example/themes/kiosk/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/0/1201314427666784/f
Video: https://d.pr/v/Doy0rH
=> [FIX] keyboard view kiosk

example/themes/kiosk/src/components/LanguageSelector/index.tsx, example/themes/kiosk/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/0/1201314427666783/f
Video: https://d.pr/v/Xtc1Xa
=> [ADD] skeleton in language selector

example/themes/original/src/components/OrderProgress/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536/1201520384683595/1201523115807390
=> Update: invalid date in order progress

example/themes/kiosk/src/components/CategoriesMenu/index.tsx, example/themes/kiosk/src/components/DrawerView/index.tsx, example/themes/kiosk/src/components/DrawerView/styles.tsx, example/themes/kiosk/src/components/ProductForm/index.tsx, example/themes/kiosk/src/components/ProductForm/styles.tsx
Story: https://app.asana.com/0/0/1201314427666761/f
Video: https://d.pr/v/lJS4bU
=> [ADD] Product as Drawer

example/themes/doordash/src/components/BusinessProductsCategories/index.tsx, example/themes/doordash/src/components/BusinessProductsList/index.tsx, example/themes/doordash/src/components/BusinessProductsListing/index.tsx, example/themes/doordash/src/components/ForgotPasswordForm/index.tsx, example/themes/doordash/src/components/ForgotPasswordForm/styles.tsx, example/themes/doordash/src/components/Help/index.tsx, example/themes/doordash/src/components/LastOrders/index.tsx, example/themes/doordash/src/components/LastOrders/styles.tsx, example/themes/doordash/src/components/ProductForm/index.tsx, example/themes/doordash/src/types/index.tsx
When you update `ordering-ui-react-native` lib, please mention on [Original Task](https://app.asana.com/0/1123879547915797/1200507278965969/f)
I need to update something on template app from this lib. thanks
=> updated doordash template fixing issues

example/src/components/AddressForm/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201489986787927/f
VIdeo: https://d.pr/v/N1rAf2
=> [ADD] google autocomplete by country

example/themes/kiosk/src/components/BusinessProductsListing/index.tsx, example/themes/kiosk/src/components/CartBottomSheet/styles.tsx, example/themes/kiosk/src/components/CategoriesMenu/index.tsx
Story: https://app.asana.com/0/0/1201588716483768/f
video: https://d.pr/v/wwS1hM
=> [FIX] align product and categories

example/src/components/ActiveOrders/index.tsx
Story:https://app.asana.com/0/1199511033583011/1201514374404486/f
=> [FIX] active orders nested scroll

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201522322436212
=> [Update]: Multiple photos feedback

example/themes/single-business/src/components/ProductForm/index.tsx, example/themes/single-business/src/components/UserProfileForm/index.tsx
https://app.asana.com/0/1191220738645130/1201602907688389
=> [FIX] feedback provided for single-business-app

example/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201627708826048/f
Image: https://d.pr/i/jvEC74
=> Remove hardcoded text

example/themes/original/src/components/ActiveOrders/index.tsx, example/themes/original/src/components/ActiveOrders/styles.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/components/BusinessTypeFilter/index.tsx, example/themes/original/src/components/BusinessTypeFilter/styles.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/BusinessesListing/styles.tsx
story: https://app.asana.com/0/1200550251832819/1201540043462899
demo: https://d.pr/v/5i1Z6V
=> Ordering Original app feedback

example/themes/doordash/src/components/ProductForm/index.tsx, example/themes/instacart/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/single-business/src/components/ProductForm/index.tsx, example/themes/uber-eats/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/0/1201489117570766/1201619700674461/f
=> apply estimate person in templates

example/themes/business/src/components/GoogleMap/index.tsx, example/themes/business/src/components/OrderDetails/Business.tsx
Story: https://app.asana.com/0/1201115702325003/1201080467133097/f
Video: https://d.pr/v/qyAggh
=> [ADD] Callout in business app map

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201640857303139
=> [Fix] feedback for customer rating

example/src/components/BusinessProductsListing/index.tsx
Story: https://app.asana.com/0/0/1201609384822489/f
Video: https://d.pr/v/nVfW0J
=> [FIX] search by product validation

example/themes/uber-eats/src/components/Account/index.tsx, example/themes/uber-eats/src/components/AddressList/index.tsx, example/themes/uber-eats/src/layouts/Container.tsx
Story: https://app.asana.com/0/0/1201664900802226/f
Video: https://d.pr/v/7UuvgT
=> [FIX] Upload image in profile

example/src/components/ActiveOrders/styles.tsx, example/themes/instacart/src/components/ActiveOrders/styles.tsx, example/themes/uber-eats/src/components/ActiveOrders/styles.tsx
Story: https://app.asana.com/0/0/1201664900802228/f
=> [FIX] active order design

example/themes/original/src/components/ActiveOrders/index.tsx, example/themes/original/src/components/BusinessTypeFilter/styles.tsx, example/themes/original/src/components/OrdersOption/index.tsx
Story: https://app.asana.com/0/1200550251832819/1201640857303147/f
Demo: https://d.pr/v/GQkRVR
https://d.pr/v/l4l2Jz
=> jan FeedBack of Original

example/src/components/Messages/index.tsx, example/src/utils/index.tsx
Story: https://app.asana.com/0/0/1201631352269175/f
=> [FIX] Add language variables

example/src/components/Messages/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201679751657428/f
Video: https://d.pr/v/ywpttL
=> [FIX] design when keyboard available

example/themes/original/index.tsx, example/themes/original/src/components/ActiveOrders/index.tsx, example/themes/original/src/components/ActiveOrders/styles.tsx, example/themes/original/src/components/MessageListing/index.tsx, example/themes/original/src/components/MessageListing/styles.tsx, example/themes/original/src/components/Messages/index.tsx, example/themes/original/src/components/Messages/styles.tsx, example/themes/original/src/components/UserProfile/index.tsx
Story : https://app.asana.com/0/1200550251832819/1201348696236216/f
Demo : https://d.pr/v/iiSqoy
=>  message page in origin template

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx, example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/shared/OTextarea.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1201683606135343/1201627022917517/f
Video: https://d.pr/v/3d7V7R
=> add-driver-zone-restriction

example/themes/uber-eats/src/components/Cart/index.tsx, example/themes/uber-eats/src/components/Cart/styles.tsx, example/themes/uber-eats/src/components/shared/OBottomPopup.tsx
Story: https://app.asana.com/0/0/1201722301312961/f
Video: https://d.pr/v/ffRMkN
=> [FIX] keyboardavoidingview

example/themes/kiosk/src/components/LanguageSelector/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201728598469376/f
=> [FIX] Apply correct language loading

example/themes/kiosk/src/components/CategoriesMenu/index.tsx
Story: https://app.asana.com/0/0/1201753090271330/f
Image: https://d.pr/i/jKg59D
=> [FIX] Product Title overlap

example/themes/original/src/components/ActiveOrders/index.tsx, example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/MyOrders/styles.tsx, example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/types/index.tsx
Story:  https://app.asana.com/0/1200550251832819/1201171418694348
Demo:  https://d.pr/v/2vep0G
=> auto loadmore in profile order page in Origin

example/themes/uber-eats/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/0/1201765641749140/f
Image:
https://d.pr/i/5EIAaD
=> [FIX] Comment box in product form

example/themes/uber-eats/src/components/Messages/index.tsx, example/themes/uber-eats/src/components/shared/OBottomPopup.tsx
Story: https://app.asana.com/0/0/1201772986582325/f
Video: https://d.pr/v/SCqoJ7
=> [FIX] when keyboard enabled design

example/src/components/ProductForm/index.tsx, example/src/components/SingleProductCard/index.tsx, example/src/components/SingleProductCard/styles.tsx
Story: 
https://app.asana.com/0/1200550251832819/1201730970795381
Demo: 
https://d.pr/v/swT9V9
https://d.pr/i/oYb94e
=> show regular price

example/src/components/BusinessProductsList/index.tsx
Story: https://app.asana.com/0/1200550251832819/1201187513910289
PR:  https://d.pr/v/HL6Sye
=> sort product by rank

example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/components/UserProfileForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201753893271021
=> Original feedback

example/themes/business/src/components/NewOrderNotification/index.tsx, example/yarn.lock
Story: https://app.asana.com/0/1200268243113852/1201816374213344
=> [Update]: Message notification title

example/themes/instacart/src/components/BusinessProductsList/styles.tsx, example/themes/instacart/src/components/SingleProductCard/index.tsx, example/themes/instacart/src/components/SingleProductCard/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1201839532453686
DEMO: https://d.pr/i/JG4qED
=> [FIX] feedback for template instacart

example/themes/original/src/components/ProductOptionSubOption/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201783090681898
=> Update: suboption

example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx
Story: https://app.asana.com/0/1200550251832819/1201694040067882
Demo: https://d.pr/v/m7cRTL
=> add product weight Original

example/themes/original/src/components/ProductForm/index.tsx
but screen : https://d.pr/i/S8kDM4
=> bug duplicated price in Origin

example/src/components/LogoutButton/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/inbox/1198717964396322
Demo: https://d.pr/v/clArYB
=> [Improve] google login for Android

example/android/build.gradle, example/src/components/ProductForm/index.tsx, example/src/components/ProductForm/styles.tsx, example/src/config.json, example/themes/doordash/src/components/ProductForm/index.tsx, example/themes/doordash/src/components/ProductForm/styles.tsx, example/themes/instacart/src/components/ProductForm/index.tsx, example/themes/instacart/src/components/ProductForm/styles.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/uber-eats/src/components/ProductForm/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1201127779652039
DEMO: https://d.pr/i/rb6T2s
=> [Feat] Product tags Information

example/themes/original/src/components/FacebookLogin/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201861274968474/f
iOS: https://d.pr/v/cniXcv
Android: https://d.pr/v/WGL2NB
=> [FIX] handle errors

example/themes/original/src/components/Home/index.tsx
Story: https://app.asana.com/0/1201859974879441/1201891314836314/f
Image: https://slack-files.com/T0D4MPDCY-F035S0RMM6D-d1aab2db1f
=> [FIX] language selector

example/themes/original/src/components/UpsellingProducts/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201930561615831/f
Video demo: https://d.pr/v/X4YHwh
=> [FIX] validate if cart emtpy

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201955103629796/f
Video: https://d.pr/v/BoaosV
=> [FIX] businesslist after login

example/src/components/BusinessesListing/index.tsx, example/themes/doordash/src/components/BusinessesListing/index.tsx, example/themes/instacart/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/BusinessPreorder/index.tsx, example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/components/MomentOption/styles.tsx, example/themes/uber-eats/src/components/BusinessesListing/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201919927062208
=> Preorder update

example/themes/original/src/components/UpsellingProducts/index.tsx
Story: https://app.asana.com/0/1199511033583011/1201955707135387/f
Video: https://d.pr/v/PZ6yx2
=> move upselling at the bottom of cart

example/src/components/Checkout/index.tsx, example/src/components/PaymentOptions/index.tsx, example/src/components/PaymentOptionsWebView/index.tsx, example/src/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/PaymentOptions/index.tsx, example/themes/original/src/components/UpsellingProducts/index.tsx
Story: https://app.asana.com/0/0/1201968710912043/f
Video RN T1: https://d.pr/v/Y74DNf
Video RN T5: https://d.pr/v/DQC6M9
=> component payment options webview

example/themes/original/src/components/ProductOptionSubOption/index.tsx
Story: https://app.asana.com/0/1200268243113852/1201974520684105
=> Update: product suboption

example/src/components/shared/OIcon.tsx
Story: https://app.asana.com/0/1201859974879441/1201971591491847/f
=> Change default lunch image

example/package.json, example/themes/original/src/components/ProductForm/index.tsx
=> add youtube video gallery

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202024330457219
=> [Fix] Canny feedback for template 5

example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/components/OrdersOption/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1201990767918422
=> Update: noOrder message

example/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1201324366625225/1202018122784459/f
Before: https://d.pr/v/Rlh0xl
After: https://d.pr/v/YThSPb
=> [FIX] redirect business listing

example/themes/original/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/1201859974879441/1201971591491847/f
Image: https://d.pr/i/05aX4E
=> FIX dummy product image

example/themes/original/src/components/shared/OInput.tsx
Story: https://app.asana.com/0/0/1202042323866674/f
=> [FIX] validate if prop exists

example/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202015942212702/f
Video: https://d.pr/v/HILYxz
=> [FIX] isDisabled when loading.

example/themes/original/src/components/UserDetails/index.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/components/UserProfileForm/index.tsx, example/themes/original/src/components/VerifyPhone/index.tsx, example/themes/original/src/components/VerifyPhone/styles.tsx, example/themes/original/src/types/index.tsx, example/yarn.lock
Story: https://app.asana.com/0/1200268243113852/1201943201966705
Demos: https://d.pr/v/xKn0IG
https://d.pr/v/SKAT4c
=> [Feat]: Phone verify on profile & checkout

example/themes/original/src/components/UserFormDetails/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536/1201943201966705/1202063166776052
=> Update: comma fix

example/themes/original/src/components/ProductForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202057642513707
=> [Fix] max quantity and zero quantity issues for the template original

example/themes/original/index.tsx, example/themes/original/src/components/ReviewDriver/index.tsx, example/themes/original/src/components/ReviewDriver/styles.tsx, example/themes/original/src/components/ReviewOrder/index.tsx, example/themes/original/src/components/ReviewOrder/styles.tsx, example/themes/original/src/components/ReviewProducts/index.tsx, example/themes/original/src/components/ReviewProducts/styles.tsx, example/themes/original/src/components/SingleProductReview/index.tsx, example/themes/original/src/components/SingleProductReview/styles.tsx, example/themes/original/src/layouts/FloatingBottomContainer.tsx, example/themes/original/src/types/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202072110042659
=> [Add] Advanced review for original template

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/OrdersOption/styles.tsx, example/themes/business/src/components/PreviousOrders/index.tsx, example/themes/business/src/components/PreviousOrders/styles.tsx
Story:
https://app.asana.com/0/inbox/1200550251832815/1201986359633429/1201897715077345
Demo: 
https://d.pr/v/A5BIvV
https://d.pr/v/dWIky9
=> add SLA setting in business theme

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202057642513698
Demo:
https://d.pr/v/yXs6Uu
https://d.pr/v/x5yTuP
=> [Fix] Canny feedback

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202094174200734/f
Video: https://d.pr/v/9xLOg5
=> [FIX] better quality images

example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/original/src/components/ProductOptionSubOption/index.tsx
Story: https://app.asana.com/0/1200550251832819/1201355475427743
Demo: https://d.pr/v/aPb2vi
=> auto scrolling to next option when select a option in Origin Template

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202076218317954/f
Video: https://d.pr/v/0knMcS
=> [FIX] validate preorder config

example/src/components/MomentOption/index.tsx
Story: https://app.asana.com/0/1202080309393054/1201929203943938/f
Video: https://d.pr/v/u1S69Z
=> [FIX] Validate config

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/Checkout/styles.tsx, example/yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202118574026499
Demo: https://d.pr/v/zjubKX
=> Update: add products button

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/OrdersOption/styles.tsx
story: https://app.asana.com/0/1200550251832819/1202141091343461
=> feedback-delayed_deadline

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1201126531558193
Demo: https://d.pr/v/7O0Grd
=> quantity limit according to minimum and maximum

example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202141091343475
Demo: https://d.pr/i/rkmyjH
=> improve to sla timer

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderDetails/styles.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202182298517672
Demo: https://d.pr/v/UtK7co
=> add Reorder in order detail screen

example/themes/original/src/components/ProductForm/index.tsx
STORY: https://app.asana.com/0/1200550251832819/1202203059399570
Demo: https://d.pr/v/akbRoF
=> add validation to product having order limit

example/themes/original/src/components/PreviousOrders/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202213233195208
=> [Fix] Review crash issue

example/themes/original/src/components/UpsellingProducts/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202144335689560
Demo: https://d.pr/i/JFqcMf
=> Update: Upselling page

example/themes/single-business/src/components/OrderTypeSelector/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202227661166857/f
=> [FIX] Change language variable text

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202226033684628
Demo: https://d.pr/v/DqyYeL
=> add validation for pre order

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/1200550251832819/1202224356221562
Demo: https://d.pr/v/HwWSjq
=> remove product from cart

example/themes/original/index.tsx
Story: https://app.asana.com/0/1201324366625225/1202223237888938/f
=> [ADD] missing exports

example/themes/original/src/components/ProductForm/index.tsx, example/yarn.lock
Story: https://app.asana.com/0/1200268243113852/1202247763630456
=> Update: product option

example/themes/original/src/components/ProductForm/index.tsx
Story : https://app.asana.com/0/home/1200550251832815/1202246510802970
Demo : https://d.pr/v/20FQqN
=> bug add video gallery

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessMenuList/index.tsx, example/themes/original/src/components/BusinessPreorder/index.tsx
https://app.asana.com/0/1191220738645130/1202248547236292
=> [ADD] missed changes for feedback april

example/themes/original/src/components/BusinessPreorder/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202253505195838
Demo: https://d.pr/v/4Jte8t
=> hide calendar when preorder is disable

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202253505195838
Demo : https://d.pr/v/4Jte8t
=> Bug feedback preorder

example/src/pages/BusinessProductsList.tsx, example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessBasicInformation/styles.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsList/styles.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/SingleProductCard/styles.tsx, example/themes/original/src/utils/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202184755900181
=> [Feat]: Ribbon

example/themes/business/src/components/OrdersListManager/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202269914718486
Demo: https://d.pr/v/VdBepg, https://d.pr/v/Vy5BVU
=> Order deadline delayed

example/themes/original/index.tsx
Story: https://app.asana.com/0/1201324366625225/1202223237888938/f
=> [FEAT] Added missing exports

example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202269914718486
Demo: https://d.pr/i/ld66Jy
=> fix time format

example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202302614830432
Demo: https://d.pr/v/mpJRsU
=> fix sla time

example/package.json, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/LoginForm/styles.tsx, example/themes/original/src/types/index.tsx, example/yarn.lock
STORY: https://app.asana.com/0/1198717964402573/1202253505195821
Demo:
android: https://d.pr/v/l3TIiW
iOS: https://d.pr/v/cB7ys7
=> [Add] Recaptcha

example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/types/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202330499490553
=> [Add] ReCaptcha for Sign up

example/themes/original/src/components/BusinessReviews/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202211257613694
=> Update: business review

example/themes/original/index.tsx
Story: https://app.asana.com/0/0/1202344399684161/f
=> [FEAT] Missing exports

example/themes/original/src/components/AddressList/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/Home/index.tsx, example/themes/original/src/components/UserProfile/index.tsx, example/themes/original/src/config/constants.tsx, example/themes/single-business/src/components/AddressList/index.tsx, example/themes/single-business/src/components/UserProfile/index.tsx
Story: https://app.asana.com/0/1202177152901831/1202213210076888/f
=> [FEAT] Language variables fix

example/src/pages/BusinessesListing.tsx, example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/components/BusinessFeaturedController/index.tsx, example/themes/original/src/components/BusinessFeaturedController/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1202342562473414
=> Update: ribbon

example/src/components/LanguageSelector/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202349022576145/f
=> [FEAT] fixAndroidTouchableBug

example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/components/MomentOption/styles.tsx
Story: https://app.asana.com/0/1199511033583011/1202269584151953/f
Video: https://d.pr/v/tyMsSJ
=> [FEAT] validation format 12 hours

example/themes/original/src/components/OrderDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202382338544000
Demo:  https://d.pr/i/eQSbKE   https://d.pr/i/OLA48m   https://d.pr/i/LbXRjF
=> [Add] new statuses for map view

example/src/utils/index.tsx, example/themes/original/src/utils/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322/1202260802722734/1202383926754331
=> [Add] traduction

example/themes/original/src/components/Wallets/index.tsx
Story: https://app.asana.com/0/1202390334219072/1202383139432347/f
Image: https://d.pr/i/YoGUmp
=> [FEAT] fix validation

example/themes/business/src/components/OrderDetails/Business.tsx
Story: https://app.asana.com/0/1199511033583011/1202382566350559/f
=> [FEAT] fix map blank screen

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
Story: https://app.asana.com/0/1199511033583011/1202354581530808/f
image: https://d.pr/i/VagG2s
=> [FEAT] show delivery option

example/src/navigators/HomeNavigator.tsx, example/src/pages/Sessions.tsx, example/themes/original/src/components/Sessions/index.tsx, example/themes/original/src/components/Sessions/styles.tsx, example/themes/original/src/components/UserProfile/index.tsx, example/themes/original/src/types/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322/1202428894771913/1202408251319319
=> [Feat] sessions

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322/1202436552306828/1202446573049098
=> [Add] allow the store to change

example/themes/original/src/components/ForgotPasswordForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202295471114432
=> [Update]: Forgot password

example/themes/original/src/components/PhoneInputNumber/index.tsx
Story: https://app.asana.com/0/1200550251832819/1202422215317925
Demo: https://d.pr/v/Uo7RRR
=> update phone number

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/UpsellingProducts/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202458647414023
=> [Fix] Cart feedback

example/src/components/LanguageSelector/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202372044669727/f
Video: https://d.pr/v/YQQrHz
=> [FEAT] change direction if rtl

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202224356221562
Demo: https://d.pr/v/RxbUQ6
=> feedback reorder

example/themes/business/src/components/NewOrderNotification/index.tsx, example/themes/business/src/components/OrdersListManager/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202458534194193/f
Driver app: https://d.pr/v/SwZYTo
Business app: https://d.pr/v/K9DiSx
=> [FEAT] update order notification fix

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322/1202458647414012/1202446573049098
=> [Fix] Feedback shared cart

example/themes/business/src/components/LoginForm/index.tsx, example/themes/business/src/components/LoginForm/styles.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202458534194187/f
Video: https://d.pr/v/K0jiHu
=> [FEAT] Recaptcha for business, delivery apps

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/BusinessListingSearch/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1202408286159614
=> [Feat]: price filter

example/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202495350549661
Demo: https://d.pr/v/J3VIGW
=> bug fix driver tip

example/themes/business/src/components/LoginForm/index.tsx
Story: https://app.asana.com/0/0/1202497258819388/f
Video: https://d.pr/v/kZK6IU
=> [FEAT] login with recaptcha

example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202439102770114/f
Video: https://d.pr/v/nQ7MhN
=> [FEAT] business list as guest

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
STORY: https://app.asana.com/0/1198717964402573/1202491794475486
=> [Fix] driver app crash error

example/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202495547847028/f
=> [FEAT] load images fix

example/themes/original/src/components/DriverTips/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202482858626302/f
Video: https://d.pr/v/Y3VnF3
=> [FEAT] driver tip options

example/themes/business/src/components/OrderDetails/Delivery.tsx
Story: https://app.asana.com/0/0/1202511616761465/f
Image: https://d.pr/i/j5OsO3
=> [FEAT] Show floating button status driver on way

example/themes/business/src/components/LogoutButton/index.tsx
Story: https://app.asana.com/0/0/1202522124261463/f
=> [FEAT] Fix local storage exclude

example/src/components/UpsellingProducts/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202474095937623
Demo: https://d.pr/i/KKNZyc?showPanel=1
=> [Fix] cut off image

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/components/PreviousOrders/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202540877098704
Demo: https://d.pr/v/Nabt7d
=> add new reorder

example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202466057833178/f
https://app.asana.com/0/1202390334219072/1202491794475497/f
Video: https://d.pr/v/HGGpP9
=> [FEAT] fix rerender map

example/src/components/DriverTips/index.tsx, example/themes/original/src/components/DriverTips/index.tsx
Story: https://app.asana.com/0/1200550251832819/1202379385928727
Demo: https://d.pr/v/KOnpQR
=> feedback driver tip

example/themes/original/src/components/shared/OInput.tsx, example/themes/original/src/types/index.tsx
Reverts Ordering-Inc/Ordering-UI-Native#893
=> Revert "add placeholder color"

example/src/navigators/CheckoutNavigator.tsx, example/src/navigators/HomeNavigator.tsx, example/src/pages/MultiCheckout.tsx, example/src/pages/MultiOrdersDetails.tsx, example/themes/original/index.tsx, example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/BusinessItemAccordion/styles.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/MultiCartsPaymethodsAndWallets/index.tsx, example/themes/original/src/components/MultiCartsPaymethodsAndWallets/styles.tsx, example/themes/original/src/components/MultiCheckout/index.tsx, example/themes/original/src/components/MultiCheckout/styles.tsx, example/themes/original/src/components/MultiOrdersDetails/SingleOrderCard.tsx, example/themes/original/src/components/MultiOrdersDetails/index.tsx, example/themes/original/src/components/MultiOrdersDetails/styles.tsx, example/themes/original/src/components/StripeElementsForm/index.tsx, example/themes/original/src/components/StripeElementsForm/naked.tsx, example/themes/original/src/components/UserDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202506830990159
=> [Add] Multi checkout

example/src/components/OrderDetails/index.tsx, example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/home/1200550251832815/1202570999300075
Demo: https://d.pr/i/3XWrhD, https://d.pr/i/78lLU1, https://d.pr/i/78lLU1, https://d.pr/i/VlK9xu
=> Bug no show phone

example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/FavoriteList/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202601976108428
=> [Update]: Favorite

example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202550344111912
=> [Fix] style issue

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/MultiCartsPaymethodsAndWallets/index.tsx, example/themes/original/src/components/MultiCheckout/index.tsx, example/themes/original/src/components/MultiOrdersDetails/SingleOrderCard.tsx, example/themes/original/src/components/MultiOrdersDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202615932124905
=> [Fix] Multi checkout feedback

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/Favorite/styles.tsx, example/themes/original/src/components/FavoriteList/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202625099398688
=> Update: favorite

example/src/theme.json, example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202647059938491
=> [Add] change store validation

example/src/components/LoginForm/index.tsx, example/src/components/LoginForm/styles.tsx, example/src/components/SignupForm/index.tsx, example/src/config.json, example/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202630333391244
Demo: https://d.pr/v/jeURQI
=> Show recaptcha

example/package.json
STORY: https://app.asana.com/0/inbox/1198717964396322/1202627803149688/1202632501682443
=> Upgrade webview

example/src/components/AddressForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202652565373414
=> [Fix] validation for current location

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/UserDetails/index.tsx, example/themes/original/src/components/UserFormDetails/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202675818264450
=> Update: checkout update

example/themes/original/src/components/LoginForm/Otp/index.tsx, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202677874577115
Demo: https://d.pr/v/c65aBt
=> Setting login email phone

example/src/components/ReviewOrder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202510793276078
=> [Update] default review qualification

example/themes/original/src/components/Favorite/index.tsx, example/themes/original/src/components/FavoriteList/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536
=> Update: favorite product

example/themes/original/src/components/BusinessBasicInformation/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202714062882767
=> Update: social network

example/themes/original/src/components/BusinessReviews/index.tsx, example/themes/original/src/utils/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202675935554889/f
Video: https://d.pr/v/Mz754t
=> [FEAT] set locale moment variables

example/src/components/LoginForm/index.tsx, example/src/components/SignupForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202630333391244
Demo: https://d.pr/v/xaBMRe
=> feedback recaptcha

example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202721157746581
=> feedback improve signup

example/src/components/ReviewOrder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202724185449071
=> [Update] review bar

example/src/pages/BusinessesListing.tsx, example/src/pages/OrderDetails.tsx, example/src/pages/ReviewDriver.tsx, example/src/pages/ReviewOrder.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/ReviewDriver/index.tsx, example/themes/original/src/components/ReviewOrder/index.tsx, example/themes/original/src/components/ReviewOrder/styles.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202677623030908
Demo: https://d.pr/v/8lDnjk
=> new review flow

example/package.json, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/SearchBar/index.tsx, example/themes/original/src/components/UserProfileForm/index.tsx, example/themes/original/src/components/shared/OInput.tsx, example/yarn.lock
=> Feedback customer app

example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/styles.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/ProfessionalProfile/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202721157746565
=> [Update]: Booking feedback

example/themes/business/src/components/OrderDetails/Business.tsx
Story: https://app.asana.com/0/1200268243113852/1202683163506038
=> [Update]: Assign driver

example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202665092619974
=> bug fix sla in delivery app

example/themes/original/src/components/OrderDetails/OrderHistory.tsx, example/themes/original/src/components/OrderDetails/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202771882778956
=> [Feat]: Order history

example/src/components/ReviewDriver/index.tsx, example/src/components/ReviewOrder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202724185449071
=> [Fix] rating bar issue

example/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
=> Custom app feedback

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/types/index.tsx
=> Customer app feedback

example/themes/original/src/components/SignupForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202778798838779
Demo: https://d.pr/v/zUH4XR
=> feedback signup settings

example/src/components/ReviewProducts/index.tsx, example/src/components/SingleProductReview/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202777189377892
=> [Update] product review

example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/styles.tsx, example/themes/original/src/components/ServiceForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202787123734963
=> Update: booking functionality

example/themes/original/src/components/AddressForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202738499254980
Demo:  https://d.pr/v/pjb0hu
=> bug business blank

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
demo: https://d.pr/v/N6TzRM,    https://d.pr/v/jAyLMJ
=> App feedback

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202792389154639
=> [Update]: Checkout update

example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202792368840123
Demo: https://d.pr/v/TneHse
=> improve order sla manager

example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/ReviewTrigger/index.tsx, example/themes/original/src/components/ReviewTrigger/styles.tsx, example/themes/original/src/components/shared/OBottomPopup.tsx, example/themes/original/src/layouts/FloatingBottomContainer.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202808927091149
Demo: https://d.pr/i/PYtAw0
=> improvement new review

example/src/components/PaymentOptionsWebView/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202801041328113
=> [Fix] Paypal cancel issue

example/src/components/BusinessInformation/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202784030699623
=> [Add] contact info

example/themes/original/src/components/shared/OBottomPopup.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202218735742289
Demo: https://d.pr/v/dHpPAT
=> feedback new review flow

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessProductsListing/styles.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202678272167115
=> [Update]: feedback

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/OrderSummary/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202821254325779
Demo: https://d.pr/v/JafkQZ
=> avaiable seat showed

example/themes/business/src/components/Chat/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202832322401783
=> Update: business app chat suggestion

example/themes/original/src/components/ProductForm/index.tsx
=> feedback crash scrolling

example/themes/original/src/components/Cart/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202821254325779
Demo: https://d.pr/v/YfeHrG
=> available seat showed

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202852021445600
Demo:  https://d.pr/v/ONqqdU
=> auto min order quantity

example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202857088980537
Demo: https://d.pr/v/g9fsI8
=> not show dummy image

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Cart/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1202772001252225
=> [Add] driver tip for multi checkout

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202778748083780
=> [Update]: fade effect

example/src/components/NotificationSetting/index.tsx, example/src/components/shared/OBottomPopup.tsx, example/src/index.tsx, example/themes/business/src/components/OrdersListManager/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/types/index.tsx, example/themes/original/src/components/BusinessesListing/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202833311662986
Demo:  https://d.pr/v/ZE7w5D
=> Detect notifications

example/themes/original/src/components/BusinessProductsList/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202646196826705
=> Update: fade effect

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderDetails/styles.tsx, example/themes/original/src/components/OrderSummary/index.tsx, example/themes/original/src/components/PlaceSpot/index.tsx, example/themes/original/src/components/PlaceSpot/styles.tsx, example/themes/original/src/types/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202899918599655
=> [Update] checkout and confirmation page for Order types

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx
Story: https://app.asana.com/0/home/1200550251832815
=> Improve app feedback

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
STORY:
https://app.asana.com/0/1198717964402573/1202925008620123
https://app.asana.com/0/1198717964402573/1202925008620126
https://app.asana.com/0/1198717964402573/1202925008620127
https://app.asana.com/0/1198717964402573/1202925008620133
Demo: 
https://d.pr/i/tj3R6F
https://d.pr/v/z5LQYU
https://d.pr/i/mNkMBM
https://d.pr/v/FJ8LiC
=> [Fix] template 5 feedback

example/themes/original/src/components/BusinessListingSearch/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202791288034084
=> [Update]: Search

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202940559411903
=> [Update] search bar clickable

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/OrdersOption/PreviousBusinessOrdered/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202976212918923/f
=> [Fix] feedback for Chew app

example/themes/original/src/components/PlaceSpot/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202939273718679
=> [Fix] Spot number issue

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
Story: https://app.asana.com/0/1200268243113852/1202963647430505
=> Update: multi currency

example/package.json, example/src/types/@fatnlazycat/react-native-recaptcha-v3/index.d.ts, example/themes/business/src/components/LoginForm/index.tsx, example/themes/kiosk/src/components/LoginForm/index.tsx, example/themes/kiosk/src/components/LoginForm/styles.tsx, example/themes/kiosk/src/types/index.d.ts, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/yarn.lock
Story: https://app.asana.com/0/1200550251832819/1202909265940554
=> Feedback recaptchav3

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202987863424944
=> bug business listening image

example/themes/original/src/components/BusinessBasicInformation/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202892928244721/f
=> [FEAT] preorder language variable change

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/MultiCheckout/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203014831730178
=> [update] multi checkout feedback

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202905969977217
Demo: https://d.pr/v/FLbXgn
=> improvement max product when order

example/themes/kiosk/src/components/LoginForm/index.tsx, example/themes/kiosk/src/types/index.d.ts
Story: https://app.asana.com/0/home/1200550251832815/1202895355715695
Note:
version update: kisok app
=> bug recaptcha v3

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203007446427735
=> [Update]: bug fix

example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/1202880926594539/1203006618554107
=> [Update] Cart Api call in checkout

example/src/config.json, example/themes/original/src/components/PlaceSpot/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203033084957848
=> [Add] validation for spot number

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/ProductItemAccordion/index.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203037079275803
=> Update: multi currency feedback

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202905969977217
=> improvement product max amount

example/themes/original/src/components/OrdersOption/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202976212918925
=> [Fix] glitch issue in business search

example/themes/original/src/components/WalletTransactions/index.tsx, example/themes/original/src/components/WalletTransactions/styles.tsx, example/themes/original/src/components/Wallets/index.tsx, example/themes/original/src/components/Wallets/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1202934813272530
=> [Update] Wallets

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1202905969977217
=> improvement max product

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202976212918925
=> [Fix] browse glitch error

example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203065075167053
=> [Fix] Feedback chew

example/src/components/BusinessProductsList/index.tsx
Story: https://app.asana.com/0/home/1200550251832815/1203073012961304
Demo: https://d.pr/v/luMXuR
=> remove duplicated key

example/src/components/Messages/index.tsx
Story: https://app.asana.com/0/1199511033583011/1202777169474504/f
=> [FEAT] improve-quality-image

example/themes/original/src/components/BusinessListingSearch/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203080510058784
=> [Update] feedback original template

example/src/components/BusinessInformation/index.tsx
Story: https://app.asana.com/0/1199511033583011/1203064865224582/f
Image: https://d.pr/i/EC6GU3
=> [FEAT] show description template 1

example/themes/original/src/components/BusinessesListing/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203131260359358
=> Update: appointments layout

example/themes/original/src/components/ProductForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203134151322726
=> [Fix] product form crash

example/src/components/BusinessProductsList/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203107590263071
=> Update: category all

example/themes/original/src/components/ReviewOrder/index.tsx, example/themes/original/src/components/ReviewProducts/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203158482862761
=> Update: product review

example/themes/original/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203166548099248
=> [Update]: cart time range

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203144781893971
=> Update: max amount of product

example/themes/original/src/components/OrderTypeSelector/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203167288267993
=> [Fix] crash error when select order type

example/src/components/SingleProductReview/index.tsx, example/src/components/SingleProductReview/styles.tsx
demo: https://prnt.sc/S9ZgiQN86GR5
=> [Add] product image when customer is reviewing the product

example/themes/original/src/components/ProfessionalFilter/index.tsx, example/themes/original/src/components/ProfessionalProfile/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536
=> [Update]: booking

example/themes/original/src/components/BusinessItemAccordion/index.tsx
demo: https://prnt.sc/HfydXSmlTlTw
=> [Fix] checkout button did not cover large words

example/src/components/SingleProductReview/index.tsx, example/src/components/SingleProductReview/styles.tsx, example/themes/original/src/components/SingleProductReview/index.tsx, example/themes/original/src/components/SingleProductReview/styles.tsx
tested in development, demo: https://prnt.sc/LNesOubr0dLV
=> [Add] product image when customer reviews

example/src/components/BusinessInformation/index.tsx, example/src/components/BusinessInformation/styles.tsx
Story: https://app.asana.com/0/1199511033583011/1203203223055406/f
Video: https://d.pr/v/fBtxAb
=> [FEAT] business information format time validation

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203219669337931
=> [Update]: professional

example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203129853422958
=> [Fix] search error in iOS

example/themes/original/src/components/ServiceForm/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536/1203219557708512/1203227580341509
=> Update: wrong API

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessProductsListing/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1203232385913038
=> [Fix] weird effect when business loading

example/themes/original/index.tsx, example/themes/original/src/components/Notifications/index.tsx, example/themes/original/src/components/Notifications/styles.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/components/UserProfile/index.tsx, example/themes/original/src/components/UserProfile/styles.ts, example/themes/original/src/types/index.tsx
demo: https://www.loom.com/share/58f5deb7e3754724a90d88c73bac17a1
=> [Add] enable/disable marketing notifications

example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203232385913038
=> [Fix] Android issue

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/ProductForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203237025908925
=> [Update] minimum order instead of maximum order

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderDetails/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1203249106622827
=> Update: order detail

example/themes/original/src/components/ProductItemAccordion/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203219557708512
=> [Update]: booking order

example/themes/original/src/components/BusinessesListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203065122920645
=> [Add] review popup condition by configs

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderDetails/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1203279260800812
=> [Update]: order details

example/themes/original/src/components/OrderDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203255720796380
=> [Add] Get directions button

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/FloatingButton/styles.tsx, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/OrderTypeSelector/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx, example/themes/original/src/components/PreviousOrders/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/components/SingleProductReview/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203051766155830
=> [update]: customer feedback

example/themes/original/src/components/ProductForm/index.tsx
demo: https://www.loom.com/share/37ef94313ab84776ba4e2aeeb6f98242
=> [Fix] product image where too zoomed

example/themes/original/src/components/BusinessBasicInformation/index.tsx
story: https://app.asana.com/0/1203068399720324/1203325265002030
demo: https://www.loom.com/share/09bf1135a08c4734b6adf27853190516
=> [Fix] error when user login after add products to cart as guest user

example/themes/original/src/components/AddressForm/index.tsx
story: https://app.asana.com/0/1203068399720324/1203330065838807
demo: https://www.loom.com/share/bd3e441e57f14ad3829b0ae31bfc7927
=> [Fix] current location button were missing

example/themes/original/src/components/AddressForm/index.tsx
demo: https://www.loom.com/share/1acb63f567994426bfc6c1e89b1d9fae
=> adding current location button as geust user

example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/OrderTypeSelector/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203051766155830
=> Update: feedback

example/themes/original/src/components/AddressForm/index.tsx
story: https://app.asana.com/0/1203068399720324/1203349078209919
demo: demo: https://www.loom.com/share/499302c897c343f7b22ed100042398f4
=> [Fix] location icon overlaping

example/themes/original/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203051766155834
=> Update: image validation

example/themes/business/src/components/ReviewCustomer/index.tsx
story: https://app.asana.com/0/1203068399720324/1203372154371223
demo: https://www.loom.com/share/8ea337f1528e48c283f073c5a86f4fce
=> [Fix] customer name displays null when its incomplete

example/themes/original/src/components/AddressDetails/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/HelpAccountAndPayment/index.tsx, example/themes/original/src/components/HelpAccountAndPayment/styles.tsx, example/themes/original/src/components/HelpGuide/index.tsx, example/themes/original/src/components/HelpOrder/index.tsx, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/components/OrderSummary/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203422376269526
=> Improvements template 5

example/themes/business/src/components/ReviewCustomer/index.tsx
story: https://app.asana.com/0/0/1203419928903923/f
demo: https://www.loom.com/share/15c16080e7c04e1692eaa5606182a610
=> [Fix] white space in customer name

example/themes/original/src/components/PhoneInputNumber/index.tsx
story: https://app.asana.com/0/1199511033583011/1203356521137926/f
demo: https://prnt.sc/fl8lSTKMm7UO
=> [Update] turn on auto complete for email and phone

example/themes/original/src/components/ServiceForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203427182085431
=> Update: product edit on cart

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/styles.tsx
Story: https://app.asana.com/0/1199511033583011/1203321758841007/f
https://d.pr/i/2ORt7N
=> [FEAT] avoid crop banner

example/themes/original/src/components/Wallets/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1203373712963408
=> [update] style

example/themes/original/src/components/OrderDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203422376269535
=> update total text

example/themes/original/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/PageBanner/index.tsx, example/themes/original/src/components/PageBanner/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1201184519566877
=> [Feat] App banner

example/themes/original/src/components/AddressDetails/index.tsx, example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/styles.tsx, example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/components/OrderProgress/styles.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductItemAccordion/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/SingleProductCard/styles.tsx, example/themes/original/src/components/StripeElementsForm/index.tsx, example/themes/original/src/components/shared/OInput.tsx
STORY: https://app.asana.com/0/1198717964402573/1203435652140185
=> App design improvements

example/themes/original/src/components/PageBanner/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203458248409509
=> [Update] page swiper loop

example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1203387989999820/f
demo: https://prnt.sc/xoHSDeR6Yh6d
=> [Add] language variables

example/themes/original/src/components/BusinessProductsListing/index.tsx
story: https://app.asana.com/0/0/1203474249598707/f
demo: https://www.loom.com/share/eaebb85551ac49988c5b37da899f4e30
=> resolving feedback

example/themes/original/src/components/BusinessProductsListing/index.tsx
story: https://app.asana.com/0/1199511033583011/1203345179111237/f
demo: https://www.loom.com/share/1688b8ee2802415c9113ce1613dac83e
=> [Add] implemented add product to cart by one click

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/styles.tsx
=> [FEAT] revet #1124

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/PlaceSpot/index.tsx, example/themes/original/src/types/index.tsx
story: https://app.asana.com/0/0/1203462140613951/f
demo App: https://www.loom.com/share/f743b7565a094dca867c49fd14eda281
=> [Update] save table number with place order

example/src/components/shared/OToast.tsx, example/themes/original/src/components/FavoriteList/index.tsx, example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/ReviewDriver/index.tsx, example/themes/original/src/components/ReviewProducts/index.tsx
story: https://app.asana.com/0/1199511033583011/1203485281884148/f
=> App bugs improvements

example/themes/business/src/components/Chat/index.tsx, example/themes/original/src/components/Messages/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203491955665388
=> [Fix]: UTC time in message

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1202956130057095
=> [Feat] ETA's functionality

example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/1199511033583011/1203481287719781/f
Video: https://d.pr/v/U7xcLF
=> [FEAT] fix-crash

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
story: https://app.asana.com/0/1199511033583011/1203534447734713/f
demo App: https://www.loom.com/share/79c30d98789543ef837d3d722bd7c12b
=> [Fix] paymethods key_langs

example/themes/original/src/components/Messages/index.tsx
story: https://app.asana.com/0/1199511033583011/1203504327525136/f
demo: https://prnt.sc/Xned83DW5sCE
=> [Add] key_lang for onLongPress options in messages

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1203524249448101/f
demo: https://prnt.sc/zyb-mQJFlQJX
=> [Add] promotions label

example/themes/original/src/components/LoginForm/Otp/index.tsx, example/themes/original/src/components/LoginForm/Otp/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203557258444956/f
demo: https://www.loom.com/share/038f2779dab2431483f3910f61c9ab83
=> [Fix] auto focus bug

example/themes/original/src/components/ProductItemAccordion/index.tsx
story: https://app.asana.com/0/1199511033583011/1203549082228825/f
demo: https://www.loom.com/share/1de7911dbc1246428c018cb580328fbe
=> [Fix] app crash when click on my carts and view order

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203607480359165
=> [Fix]: professional times

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/shared/OLink.tsx
Story: https://app.asana.com/0/1200268243113852/1203614028974509
=> [Fix]: address for driver app

example/themes/original/src/components/AddressList/index.tsx, example/themes/original/src/components/AddressList/styles.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/HelpAccountAndPayment/index.tsx, example/themes/original/src/components/HelpAccountAndPayment/styles.tsx, example/themes/original/src/components/HelpGuide/index.tsx, example/themes/original/src/components/HelpGuide/styles.tsx, example/themes/original/src/components/HelpOrder/index.tsx, example/themes/original/src/components/HelpOrder/styles.tsx, example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/Notifications/index.tsx, example/themes/original/src/components/Notifications/styles.tsx, example/themes/original/src/components/UserProfileForm/index.tsx, example/themes/original/src/components/UserProfileForm/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203582490127028/f
=> Customer app comments

example/themes/original/src/components/Notifications/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203621712348910/f
=> [Fix] app crash

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/shared/OLink.tsx, example/themes/business/src/components/shared/OText.tsx
Story: https://app.asana.com/0/inbox/1200268243109536/1203617107794997/1203614260391016
=> [Update]: address display for driver app

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/FloatingButton/index.tsx, example/themes/original/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1203607480691348/f
demo: https://www.loom.com/share/54c8849bb8f34930b9e869bf107b705e
=> [Update] show view order button with multi business checkout enabled

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/Favorite/index.tsx, example/themes/original/src/components/Help/index.tsx, example/themes/original/src/components/HelpGuide/index.tsx, example/themes/original/src/components/HelpGuide/styles.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductOptionSubOption/index.tsx, example/themes/original/src/components/Sessions/index.tsx, example/themes/original/src/components/Sessions/styles.tsx, example/themes/original/src/components/UpsellingProducts/index.tsx, example/themes/original/src/components/UserProfileForm/index.tsx, example/themes/original/src/components/UserProfileForm/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203582490127028/f
=> [Fix] titles and rows

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/ProductForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1203582422462680/f
demo: https://www.loom.com/share/176d85b3c09f467c89d51ae29cf49ca3
=> [Fix] minimun to order on product form from search

example/themes/original/src/components/MessageListing/index.tsx, example/themes/original/src/components/ProductForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1203582490127028/f
=> resolving comments

example/themes/original/src/components/AddressList/index.tsx, example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/components/OrderTypeSelector/index.tsx
story: https://app.asana.com/0/1199511033583011/1203582490127028/f
=> [Fix] align titles

example/themes/business/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203617324045392
=> [Bug]: comment for driver app

example/themes/business/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203656156360953
=> [Bug]: read more for comment in driver app

example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/SingleProductCard/styles.tsx
Story: https://app.asana.com/0/1199511033583011/1203511965605503/f
=> [FEAT] show tags in single card

example/themes/original/src/utils/index.tsx
Story: https://app.asana.com/0/0/1203703089159759/f
Image: https://d.pr/i/GgFyGt
=> [FEAT] fix invalid hook call

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/PageBanner/index.tsx, example/themes/original/src/components/PageBanner/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1203617107794972
=> [Add] banner link functionality

example/themes/business/src/components/MapView/index.tsx
story: https://app.asana.com/0/1199511033583011/1203704520038930/f
=> [Fix] driver location not updated in map

example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/SingleProductCard/styles.tsx
Story: https://app.asana.com/0/0/1203713407743882/f
Image: https://d.pr/i/YcI61r
=> [FEAT] improve-show-tags-scrollable

example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/Sessions/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203630157670094/f
=> Qa web app fixes

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/DriverTips/index.tsx
story: https://app.asana.com/0/1199511033583011/1203713044564795/f'
demo: https://d.pr/v/5dHheo
=> [Add] tips with custom tips button

example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx
story: https://app.asana.com/0/1199511033583011/1203569999420089/f
=> [Fix] active orders does not appear

example/themes/business/src/components/LoginForm/Otp/index.tsx, example/themes/business/src/components/LoginForm/index.tsx, example/themes/business/src/types/index.tsx, example/themes/kiosk/src/components/LoginForm/index.tsx
STORY: https://app.asana.com/0/1199511033583011/1203512546616317/f
=> [Fix] OTP login feedback

example/themes/original/src/components/GiftCard/RedeemGiftCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203617368499239
=> [update] redeemed gift card info

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/types/index.tsx, example/themes/original/src/utils/index.tsx
Story: https://app.asana.com/0/1200268243113852/1202884440279618
=> [Feat]: guest checkout

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/ProfessionalFilter/SingleProfessionalCard/index.tsx, example/themes/original/src/components/ProfessionalFilter/index.tsx, example/themes/original/src/components/ProfessionalProfile/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx, example/themes/original/src/types/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203790174022658
=> Appointments feedback

example/themes/original/src/components/ProfessionalProfile/index.tsx, example/themes/original/src/components/ServiceForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203698455623960
=> [Add] Schedule color

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/1199511033583011/1203811702247996/f
https://d.pr/v/JghtG4
=> [FEAT] fix more text overflow

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx, example/themes/business/src/components/OrderMessage/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/ReviewCustomer/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx
story: https://app.asana.com/0/1199511033583011/1203827976826192/f
=> [Update] arrows and icons updated

example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203820032989925
=> [Update]: guest checkout feedback

example/themes/original/src/components/DriverTips/index.tsx
story: https://app.asana.com/0/1199511033583011/1203713044564795/f
=> [Fix] custom tips for multi business checkout

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/shared/OModal.tsx
sotry: https://app.asana.com/0/1199511033583011/1203827976826190/f
=> [Update] modal arrow styles

example/themes/business/src/components/DriverMap/index.tsx
story: https://app.asana.com/0/1199511033583011/1203790302222660/f
=> [Update] dialog pop up for maps link were updated

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/Home/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203845279853671
=> [Add] order functionality without address

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1203803620267194
=> [Update]: login for guest checkout

example/themes/original/src/components/BusinessBasicInformation/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203863672708839
=> [Fix] previous business header image issue

example/themes/original/src/components/MomentOption/index.tsx
story: https://app.asana.com/0/1203637309747495/1203871219905587/f
=> [Fix] customer-app-crashing

example/themes/original/src/components/UserProfile/index.tsx
story: https://app.asana.com/0/0/1203888243286536/f
=> [Fix] config validation

example/themes/business/src/components/OrderDetailsLogistic/index.tsx, example/themes/business/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1203863016401817/f
=> [Fix] accept or reject orders after click notification

example/themes/original/src/components/OrderDetails/OrderEta.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203876100023592
=> [Update] ETA functionality

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx
story: https://app.asana.com/0/1199511033583011/1203827976826192/f
=> [Update] arrow icon

example/themes/original/src/components/MessageListing/index.tsx, example/themes/original/src/components/Messages/index.tsx, example/themes/original/src/components/shared/OModal.tsx
STORY: https://app.asana.com/0/1198717964402573/1203827976826217
=> [Fix] Messages are not marked as read

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/SingleProductReview/styles.tsx, example/themes/original/src/components/shared/OButton.tsx
story: https://app.asana.com/0/1199511033583011/1203840893409918/f
=> [Fix] customer key_lang for card on delivery

example/themes/original/src/components/BusinessBasicInformation/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203861218598471/f
=> [Fix] ribbon cropped

example/themes/business/src/components/Chat/index.tsx, example/themes/original/src/components/Messages/index.tsx
story: https://app.asana.com/0/1199511033583011/1203827976826203/f
=> [Fix] do not show message suggestions after order ends

example/themes/business/src/components/GoogleMap/index.tsx, example/themes/business/src/components/MapView/index.tsx
story: https://app.asana.com/0/0/1203894149475099/f
=> [Fix] crash selecting an order

example/themes/original/src/components/PaymentOptions/index.tsx, example/themes/original/src/components/StripeCardsList/index.tsx
story: https://app.asana.com/0/1199511033583011/1203802187527538/f
=> [Update] show stripe popup when there is not cards

example/themes/business/src/components/LoginForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203885310857354
=> [Fix] OTP Login UI

example/themes/original/src/components/SignupForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1203885794612298/f
=> [Fix] missing key_langs for sign up form

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessBasicInformation/styles.tsx, example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/components/BusinessFeaturedController/index.tsx, example/themes/original/src/components/BusinessFeaturedController/styles.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsList/styles.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/SingleProductCard/styles.tsx, example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1203314742789753/f
=> [Update] ribbon with white bg

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx
story: https://app.asana.com/0/1199511033583011/1203941968964886/f
=> [Fix] reject order was not working

example/themes/original/src/components/Promotions/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203831097899136/f
=> [Update] space between promos

example/themes/original/src/components/Promotions/index.tsx, example/themes/original/src/components/Promotions/styles.tsx
story: https://app.asana.com/0/1199511033583011/1203831097899136/f
=> [Update] promotions styles

example/themes/original/src/components/AnalyticsSegment/index.tsx, example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/CouponControl/index.tsx, example/themes/original/src/components/PageBanner/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/Promotions/index.tsx, example/themes/original/src/components/UpsellingProducts/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203958790153743
=> [Add] Segment events

example/themes/original/src/components/GiftCard/PurchaseGiftCard/index.tsx, example/themes/original/src/components/GiftCard/PurchaseGiftCard/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1203946316439074
=> [Fix] Scroll issue in gift cards

example/themes/business/src/components/NewOrderNotification/index.tsx
story: https://app.asana.com/0/1199511033583011/1203962221634099/f
=> [Fix] order number does not match with pop up

example/themes/original/src/components/AddressForm/index.tsx
Story: https://app.asana.com/0/1201894042190305/1203994107793774/f
Image: https://d.pr/i/KXK4cc
=> [FEAT] fix display button

example/themes/original/src/components/Promotions/index.tsx
Story: https://app.asana.com/0/1201894042190305/1204005963019623/f
=> [FEAT] fix scroll container promotions

example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/PageBanner/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203978272594919
=> [Update] page banner navigation for hardware back press

example/themes/original/src/components/AnalyticsSegment/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204016242406082
=> [Add] Segment Wishlisting Events

example/themes/original/src/components/BusinessReviews/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204006284606825
=> [Fix] review time issue

example/src/utils/index.tsx, example/themes/kiosk/src/components/PhoneInputNumber/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204013805466899
=> [Fix] PhoneInput crash for invalid default country code in Kiosk app

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessBasicInformation/styles.tsx, example/themes/original/src/components/BusinessListingSearch/index.tsx, example/themes/original/src/components/BusinessListingSearch/styles.tsx, example/themes/original/src/components/PageBanner/index.tsx, example/themes/original/src/components/PageBanner/styles.tsx, example/themes/original/src/components/UserProfile/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1203981538650251
=> Improvement customer app

example/themes/business/src/components/NewOrderNotification/index.tsx
story: https://app.asana.com/0/1199511033583011/1203996181420748/f
=> [Fix] new order pop were not showing

example/themes/original/src/components/UserProfile/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204040759109258
=> [Fix] notification setting display issue

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/CitiesControl/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204069366743883
=> [Fix]: city filter

example/themes/original/src/components/BusinessPreorder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204007800116200
=> [Fix] Time format in the preorder

example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/OrderSummary/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204008411469418/f
=> [FEAT] validation-cart-comment-field

example/themes/business/src/components/DriverMap/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204082070098324/f
=> [FEAT] driver-map-language-variable

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessBasicInformation/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1204067541193883
=> [Update]: fix cropping of the business banner image

example/themes/original/src/components/SingleOrderCard/index.tsx
story: https://app.asana.com/0/1199511033583011/1204006284606863/f
=> [Fix] reorder button not showing in finished orders

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/0/1204106130196058/f
=> [FEAT] feedback

example/themes/business/src/components/OrderSummary/index.tsx
story: https://app.asana.com/0/1199511033583011/1203920301715367/f
=> [Feat] bluetooth permissions context

example/themes/original/src/components/OrderDetails/OrderEta.tsx, example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/1201894042190305/1204125195914046/f
=> [Fix] preorder status for eta

example/themes/original/src/components/ProductOptionSubOption/index.tsx
story: https://app.asana.com/0/0/1203821786952349/f
=> [Fix] on press product suboptions

example/themes/original/src/components/StripeCardsList/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204131046139868/f
=> [FEAT] fix stripe add card

example/themes/business/src/components/NewOrderNotification/index.tsx
story: https://app.asana.com/0/1201894042190305/1203990840807027/f
=> [Fix] infinite sound loop afeter new notifications arrive

example/themes/original/src/components/OrderDetails/OrderEta.tsx
Story: https://app.asana.com/0/1201894042190305/1204125948884226/f
Video: https://d.pr/v/xJbiPA
=> [FEAT] add-delivered-in-eta-time

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/ProductForm/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1204131046139864
=> Update: customer feedback

example/themes/original/src/components/SignupForm/index.tsx
story: https://app.asana.com/0/1201894042190305/1204134175171031/f
=> [Add] validation for key lang

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
STORY: https://app.asana.com/0/1198717964402573/1204146199887055
=> Store app distance

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
Story: https://app.asana.com/0/inbox/1200268243109536
=> [Update]: order cash amount

example/themes/original/src/components/OrderDetails/OrderHistory.tsx
story: https://app.asana.com/0/1201894042190305/1204125195914046/f
=> [Fix] time added by driver in order history

example/themes/original/src/components/PhoneInputNumber/index.tsx, example/themes/original/src/utils/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204168656644139
=> [Fix] verification screen crash

example/themes/original/src/components/ReviewProducts/index.tsx
story: https://app.asana.com/0/1201894042190305/1204013908283660/f
=> [Fix] products images

example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/utils/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204154517834759
=> [Update]: order progress on business list page

example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1201894042190305/1204127400067789/f
=> [Fix] progress bar percentage

example/themes/original/src/components/OrderDetails/OrderEta.tsx, example/themes/original/src/components/OrderDetails/OrderHistory.tsx
Story: https://app.asana.com/0/0/1204184838909186/f
=> [FEAT] add-preparation-eta-time

example/themes/original/src/components/SingleOrderCard/index.tsx
story: https://app.asana.com/0/1201894042190305/1204013908283660/f
=> [Fix] review button for pick up

example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx, example/themes/business/src/components/ReviewCustomer/index.tsx
Story: https://app.asana.com/0/inbox/1200268243109536/1204164641394051/1204180089980277
=> [Update]: Driver app feedback

example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/1201894042190305/1204195062050683/f
=> [Fix] remove code from orderDetails

example/package.json, example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/GPSButton/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/types/index.tsx
Story: 
https://app.asana.com/0/1199511033583011/1204176823579763/f
https://app.asana.com/0/1201894042190305/1204183389987468/f
=> Geocoder int

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1204198158111224/f
=> [Fix] vibrate crash

example/themes/original/src/components/OrderDetails/OrderEta.tsx
STORY: https://app.asana.com/0/1198717964402573/1204106132707175
=> [Update] order eta

example/themes/original/src/components/GPSButton/index.tsx
Story: https://app.asana.com/0/0/1204204847045888/f
=> [FEAT avoid doble inicialization

example/themes/original/src/components/GiftCard/RedeemGiftCard/index.tsx, example/themes/original/src/components/Wallets/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204136960622304
=> Gift card feedback

example/themes/original/src/components/Wallets/index.tsx
story: https://app.asana.com/0/1199511033583011/1204218963691349/f
=> [Fix] wallet title align

example/themes/business/src/components/DriverSchedule/index.tsx, example/themes/business/src/components/UserProfileForm/index.tsx
=> Driver schedule

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx
Story: https://app.asana.com/0/0/1204226563945112/f
=> Fix-update-pin-map

example/themes/original/src/components/UserProfile/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204227035187559/f
Video: https://d.pr/v/x1Zmwn
=> [FEAT] fix height con user profile

example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/Wallets/index.tsx, example/themes/original/src/components/Wallets/styles.tsx
story: https://app.asana.com/0/1199511033583011/1204218963691349/f
=> [Update] remove back button from wallet view

example/themes/original/src/components/AddressForm/index.tsx
Story: https://app.asana.com/0/0/1204251177366743/f
Video: https://d.pr/v/kQbHdX
=> [FEAT] fix new location update

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderSummary/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204156116024900
=> [Update]: display delivery fee when delivery zone price is zero

example/themes/original/src/components/OrderProgress/index.tsx
Story: https://app.asana.com/0/1201894042190305/1204125948884226/f
=> [FEAT] remove duplicate eta order time

example/themes/business/src/components/OrderDetails/Delivery.tsx
STORY: https://app.asana.com/0/1198717964402573/1204169431706067
=> [Update] validation allowed to reject an order

example/themes/business/src/components/Chat/index.tsx, example/themes/business/src/components/NewOrderNotification/index.tsx, example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
story: https://app.asana.com/0/1201894042190305/1203990840807027/f
=> [Fix] infinite loop sound when send a lot of unique messages

example/themes/original/src/components/UserFormDetails/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1204273225729319
=> [Bug]: fix style for sentry error

example/src/components/PhoneInputNumber/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204301024145881
=> [Fix] phone number crash

example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204301023785937
=> [Fix] Preorders not showing

example/themes/original/src/components/OrdersOption/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204342075326523
=> [Fix] duplicated message

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1204323467319784
=> [Bug]: icon overlap on business banner

example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/PreviousOrders/OrderItem.tsx
STORY: https://app.asana.com/0/1198717964402573/1204330702966195
=> [Fix] Delivery assignment issue

example/themes/original/src/components/Wallets/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204275409601852
=> [Bug]: duplicate view

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204257519316134
=> [Bug]: API endpoint with undefined

example/themes/original/src/components/BusinessInformation/index.tsx, example/themes/original/src/components/ScheduleAccordion/index.tsx
story: https://app.asana.com/0/1199511033583011/1204277077371838/f
=> Hour format

example/themes/original/src/components/BusinessProductsCategories/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204264713878609
=> [Bug]: Text render issue

example/themes/original/src/components/BusinessPreorder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204356560177576
=> [Fix] moment change issue

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx
Story: https://app.asana.com/0/1200268243113852/1204376528899439
=> [Bug]: banner icon overlap

example/themes/original/src/components/BusinessBasicInformation/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322/1203981538650256/1203997594988473
=> [Fix] crash error

example/themes/original/src/components/ProductItemAccordion/index.tsx
story: https://app.asana.com/0/0/1204393589764418/f
=> [Fix] sort product items by rank

example/themes/business/src/components/NewOrderNotification/index.tsx
story: https://app.asana.com/0/1199511033583011/1204400140007061/f
=> [Fix] AL order id

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204402792644899
=> [Update] reject comment attribute

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/0/1204435849616498/f
=> [FEAT] Reapply change

example/themes/business/src/components/OrderSummary/index.tsx
story: https://app.asana.com/0/1199511033583011/1204412897690504/f
=> [Fix] null in customer name when print

example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
STORY: https://app.asana.com/0/1198717964402573/1204412434089100
=> [Update] full business address notes for driver app

example/themes/original/src/components/MyOrders/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204433056764237
=> [Fix] duplicated preorders issue

example/themes/original/src/components/BusinessPreorder/index.tsx, example/themes/original/src/components/MomentOption/index.tsx, example/themes/original/src/components/MomentSelector/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204450936176463
=> [Update] time format

example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204470920354455
=> [Fix] add product one click issue

example/themes/original/src/components/BusinessInformation/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204335314395668
=> [Feat]: delivery zone on business map

example/themes/business/src/components/PreviousOrders/OrderItem.tsx
STORY: https://app.asana.com/0/1198717964402573/1204479854887000
=> [Fix] date format issue

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx, example/themes/original/src/components/ProductForm/index.tsx
story: https://app.asana.com/0/1201894042190305/1204504928660137/f
=> [Fix] margin and product image height

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx
story: https://app.asana.com/0/1201894042190305/1204512826591280/f
=> [Update] near business limit were removed

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
Story: https://app.asana.com/0/1200268243113852/1204493713837286
=> [Bug]: driver tip on order detail

example/themes/original/src/components/OrderProgress/index.tsx
story: https://app.asana.com/0/1201894042190305/1204522296664774/f
=> [Update] remove static string in order progress component

example/themes/business/src/components/PreviousOrders/OrdersGroupedItem.tsx
STORY: https://app.asana.com/0/1198717964402573/1204479854887000
=> [Fix] time format issue in driver and store app

example/themes/business/src/components/DriverSchedule/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204532883109516
=> [Fix] driver schedule time style issue

example/themes/original/src/components/SingleOrderCard/index.tsx
story: https://app.asana.com/0/1199511033583011/1204523687204290/f
=> [Fix] hide reorder & review buttons for v4 orders in v5 app

example/themes/business/src/components/UserProfileForm/index.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1204023371990854/1204532885151632/f
=> [FEAT] isHideDriverStatus

example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductOptionSubOption/index.tsx, example/themes/original/src/components/ProductOptionSubOption/styles.tsx
story: https://app.asana.com/0/1199511033583011/1204571942384098/f
=> [Add] plastic bag image

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/home/1200268243109536/1204573383374716
=> [Update]: guest-checkout feedback

example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/1199511033583011/1204523687204290/f
=> [Fix] hide reorder button from orders without cart

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
STORY: https://app.asana.com/0/1198717964402573/1204571942895386
=> [Fix] show pay method

example/themes/original/src/components/ProductForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1204571942384098/f
=> [Fix] subotion image

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/OrderProgress/index.tsx, example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1201894042190305/1204578864994280/f
=> [Add] status bar for pick up

example/themes/original/src/components/BusinessInformation/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204612382426224
=> [Update]: business delivery zone

example/themes/original/src/components/PaymentOptions/index.tsx
story: https://app.asana.com/0/1201894042190305/1204568938745166/f
=> [Fix] apple pay required fields

example/themes/original/src/components/GiftCard/RedeemGiftCard/index.tsx, example/themes/original/src/components/LastOrder/index.tsx, example/themes/original/src/components/LastOrders/index.tsx, example/themes/original/src/components/OrderProgress/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204591370980134
=> Gift cards

example/themes/original/src/components/BusinessInformation/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204621372250858
=> [Update]: delivery zone

example/themes/original/src/components/PaymentOptions/index.tsx, example/themes/original/src/components/ProductForm/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204651295061177
=> [Udpate]: guest checkout

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
Story: https://app.asana.com/0/1200268243113852/1204630994493656
=> [Update]: table number

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204624666095972
=> [Fix] keyboard issue

example/themes/business/src/components/FloatingButton/index.tsx, example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/OrderDetailsLogistic/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/PreviousOrders/OrderList.tsx, example/themes/business/src/components/PreviousOrders/index.tsx
Story: https://app.asana.com/0/0/1204661905430972/f
Video: https://d.pr/v/9ZRgnt
=> [FEAT] isHideRejectButtons

example/themes/original/src/components/GiftCard/GiftCardUI/index.tsx, example/themes/original/src/components/GiftCard/PurchaseGiftCard/index.tsx, example/themes/original/src/components/GiftCard/RedeemGiftCard/index.tsx, example/themes/original/src/components/NavBar/index.tsx, example/themes/original/src/components/Wallets/index.tsx, example/themes/original/src/components/Wallets/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1204659876312050
=> Design improvements

example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx
Story: https://app.asana.com/0/0/1204695885179041/f
=> [FEAT] improve product loading

example/themes/original/src/components/OrderDetails/index.tsx
Reverts Ordering-Inc/Ordering-UI-Native#1367
=> Revert "Customer feedback"

example/themes/business/src/components/MapView/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204741611067425/f
=> [FEAT] fix

example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/1201894042190305/1204578864994280/f
=> [Fix] progress bar when order type is pick up

example/package.json, example/themes/original/index.tsx, example/themes/original/src/components/DatePicker/index.tsx, example/themes/original/src/components/DatePicker/styles.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/components/UserFormDetails/styles.tsx
story: https://app.asana.com/0/1199511033583011/1204566686293757/f
=> [Feat] birthdate field

example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204592094895327
=> [Update] banner for business

example/themes/original/src/components/BusinessProductsListing/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204771586300616
=> [Update]: fix product load for subcategory

example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/Cart/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204786876454775
=> [Fix] gift card cart

example/themes/business/src/components/MessagesOption/index.tsx, example/themes/business/src/components/OrdersListManager/index.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/components/WebsocketStatus/index.tsx, example/themes/business/src/components/WebsocketStatus/styles.tsx
STORY: https://app.asana.com/0/1198717964402573/1203518580476079
=> [Add] Websocket Connection Status

example/src/utils/index.tsx, example/themes/business/src/components/OrdersListManager/utils.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/original/src/components/BusinessListingSearch/MaxSectionItem/index.tsx
Story: https://app.asana.com/0/1199511033583011/1204735396231387/f
=> Variable-minutes-change

example/themes/business/index.tsx, example/themes/business/src/components/BusinessProductList/AccordionDropdown.tsx, example/themes/business/src/components/BusinessProductList/IterateCategories.tsx, example/themes/business/src/components/BusinessProductList/ProductList.tsx, example/themes/business/src/components/BusinessProductList/index.tsx, example/themes/business/src/components/BusinessProductList/styles.tsx
Story: https://app.asana.com/0/home/1200268243109536/1204758891869340
=> [Update]: allow enable/disable category and product for store app

example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/SingleOrderCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204759012858338
=> [Fix] Feedback gift card

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
Story: https://app.asana.com/0/1204023371990854/1204796272180708/f
=> [FEAT] show-external-id

example/themes/original/src/components/ProductForm/ActionButton.tsx, example/themes/original/src/components/ProductForm/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204794648782649
=> [Fix] address list redirect for unaddressed order

example/themes/business/src/components/BusinessController/index.tsx, example/themes/business/src/components/StoresList/index.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204807196132851
=> [Update]: Add product category

example/themes/business/src/components/BusinessProductList/ProductList.tsx, example/themes/business/src/components/BusinessProductList/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204816731553719
=> [Update]: allow category and product

example/themes/original/src/components/DatePicker/index.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/components/UserFormDetails/styles.tsx
story: https://app.asana.com/0/1199511033583011/1204566686293757/f
=> [Update] date picker component

example/themes/business/src/components/OrderDetails/Delivery.tsx
Story: https://app.asana.com/0/1199511033583011/1204834609758487/f
=> [FEAT] permission-always-requiered

example/themes/business/src/components/BusinessProductList/ProductList.tsx, example/themes/business/src/components/BusinessProductList/index.tsx, example/themes/business/src/components/SearchBar/index.tsx, example/themes/business/src/components/StoresList/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204844651273894
=> [Update]: category product feedback

example/themes/original/src/components/ProductForm/index.tsx
story: https://app.asana.com/0/1201894042190305/1204649092708318/f
=> [Fix] lang key for comment title section

example/themes/original/src/components/BusinessController/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204856679295816
=> [Update]: fix long businss name

example/themes/original/src/components/LoginForm/Otp/index.tsx
story: https://app.asana.com/0/1199511033583011/1204891776318132/f
=> [Fix otp crash

example/themes/original/src/components/BusinessController/index.tsx, example/themes/original/src/components/BusinessController/styles.tsx, example/themes/original/src/components/HighestRatedBusinesses/index.tsx
Story: https://app.asana.com/0/1200268243113852/1204907750176190
=> [Update]: fix business address view

example/themes/original/src/components/Cart/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204788733539129
=> [Fix] checkout navigation issue for gift card

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx
Story: https://app.asana.com/0/1200268243113852/1204789948856832
=> [Update]: hide hash key

example/themes/business/src/components/UserProfileForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1204907631459474/f
=> [Fix] upload profile image

example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/CartContent/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/GiftCard/SendGiftCard/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204908336467994
=> [Fix] gift card feedback

example/themes/original/src/components/PaymentOptionCard/index.tsx, example/themes/original/src/components/StripeCardsList/index.tsx
story: https://app.asana.com/0/1199511033583011/1204940794384629/f
=> [Fix] stripe connect crash

example/themes/business/src/components/OrderSummary/index.tsx
story: https://app.asana.com/0/1199511033583011/1204956995007857/f
=> [Fix] show all payment methods in order details

example/themes/original/src/components/PaymentOptions/index.tsx, example/themes/original/src/components/StripeCardsList/index.tsx, example/themes/original/src/components/StripeElementsForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1204940794384629/f
=> [Fix] stripe connect issue after add a card

example/themes/business/src/components/OrderSummary/index.tsx, example/themes/business/src/components/ProductItemAccordion/index.tsx
story:: https://app.asana.com/0/1199511033583011/1204956873487905/f
=> [Fix] subtotal & order summary fixes

example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
story: https://app.asana.com/0/1199511033583011/1204956995007857/f
=> [Fix] paymethods in a new orden coming from socket

example/themes/business/src/components/NewOrderNotification/index.tsx
=> [FEAT] show inapp with status from setting

example/themes/business/index.tsx, example/themes/business/src/components/Sessions/index.tsx, example/themes/business/src/components/Sessions/styles.tsx, example/themes/business/src/components/UserProfileForm/index.tsx, example/themes/business/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1204945030371116/f
=> [Feat] manage sessions for driver and business app

example/themes/original/src/components/GiftCard/GiftCardOrdersList/index.tsx, example/themes/original/src/components/GiftCard/GiftCardOrdersList/styles.tsx, example/themes/original/src/components/GiftCard/SingleGiftCard/index.tsx, example/themes/original/src/components/GiftCard/SingleGiftCard/styles.tsx, example/themes/original/src/components/GiftCard/VerticalGiftCardOrdersLayout/index.tsx, example/themes/original/src/components/GiftCard/VerticalGiftCardOrdersLayout/styles.tsx, example/themes/original/src/components/MyOrders/index.tsx, example/themes/original/src/components/OrdersOption/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1204585344079816
=> [Add] Gift card orders

example/themes/original/src/components/SingleOrderCard/index.tsx
story: https://app.asana.com/0/1201894042190305/1205007135783186/f
=> [Fix] show total from a mbc in my orders

example/themes/business/src/components/OrderSummary/index.tsx
story: https://app.asana.com/0/1199511033583011/1205000776535312/f
=> [Fix] delivery fee mount in print component

example/themes/original/src/components/MultiOrdersDetails/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205013183079625
=> [Fix] back button not working

example/themes/business/src/components/OrderDetails/Delivery.tsx, example/themes/business/src/components/OrdersOption/index.tsx, example/themes/business/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1204921712312370/f
=> [Feat] combine tabs and hide timer

example/themes/business/src/components/Sessions/index.tsx
story: https://app.asana.com/0/1199511033583011/1204945030371116/f
=> [Update] show the newest session at the top

example/themes/business/src/components/Home/index.tsx, example/themes/business/src/components/shared/OInput.tsx
STORY: https://app.asana.com/0/1198717964402573/1204994577260620
=> [Update] don't allow project name

example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205045448144252
=> [Fix] driver tip require issue for gift card

example/themes/original/src/components/MultiCheckout/index.tsx
story: https://app.asana.com/0/1201894042190305/1205059640110139/f
=> [Fix] crash in mbc

example/themes/original/src/components/Home/index.tsx, example/themes/original/src/components/shared/OButton.tsx
story: https://app.asana.com/0/0/1204980115529368/f
=> [Fix] button color from theme

example/themes/original/src/components/ProductItemAccordion/index.tsx
story: https://app.asana.com/0/1201894042190305/1205059640110139/f
=> [Fix] product quantity warnings and rendering issue

example/themes/original/src/components/Cart/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205045448144225
=> [Fix] gift card checkout issue

example/themes/original/src/components/Home/index.tsx, example/themes/original/src/components/shared/OButton.tsx
story: https://app.asana.com/0/0/1205105655027298/f
=> [Fix] theme crash and colors issue in proyects that have not set a color

example/themes/original/src/components/Checkout/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205105136262367
=> [Fix] crash bug

example/themes/original/src/components/ProductItemAccordion/index.tsx, example/themes/original/src/components/ProductItemAccordion/styles.tsx
story: https://app.asana.com/0/1201894042190305/1205113020783156/f
=> [Fix] comments out of position in order details

example/themes/original/src/components/PaymentOptions/index.tsx
story: https://app.asana.com/0/1199511033583011/1205145085063477/f
=> [Fix] stripe add card issue

example/themes/original/src/components/PaymentOptions/index.tsx, example/themes/original/src/components/StripeCardsList/index.tsx
story: https://app.asana.com/0/1199511033583011/1205145085063477/f
=> [Fix] refresh card when added

example/themes/original/src/components/BusinessesListing/Layout/Original/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205087665448325
=> [Fix] featured businesses not loaded

example/themes/original/src/components/BusinessController/index.tsx
story: https://app.asana.com/0/1199511033583011/1205146198376883/f
=> [Update] add the word discount in the offer ribbon

example/themes/original/src/components/BusinessController/index.tsx
story: https://app.asana.com/0/1199511033583011/1205146198376883/f
=> [Fix] validate when discount its 0

example/themes/original/src/components/AnalyticsSegment/index.tsx, example/themes/original/src/components/BusinessProductsListing/index.tsx
STORY: https://app.asana.com/0/inbox/1198717964396322
=> [Update] Segment

example/themes/original/src/components/UserFormDetails/index.tsx
story: https://app.asana.com/0/1199511033583011/1205198766232852/f
=> [Fix] input cropped when on click to open calendar

example/themes/business/src/components/PreviousOrders/OrderItem.tsx
story: https://app.asana.com/0/1199511033583011/1205220812648142/f
=> [Feat] add setting to show external id instead of order id

example/themes/original/src/components/StripeElementsForm/index.tsx, example/themes/original/src/components/StripeElementsForm/naked.tsx
STORY: https://app.asana.com/0/1198717964402573/1205223756853639
=> [Fix] Stripe issue for gift card

example/themes/business/src/components/PreviousOrders/OrderItem.tsx
story: https://app.asana.com/0/1199511033583011/1205173502258497/f
=> [Fix] missing lang_key for delayed time

example/themes/business/src/components/MapView/index.tsx
Story: https://app.asana.com/0/1204253144878136/1204866769810351/f
=> [FEAT] fix sentry issues

example/themes/business/src/components/PhoneInputNumber/index.tsx, example/themes/business/src/utils/index.tsx
STORY: https://app.asana.com/0/1198717964402573/1205265964833999
=> [Fix] login crash by phone

example/themes/original/src/components/SignupForm/index.tsx, example/themes/original/src/components/UserFormDetails/index.tsx, example/themes/original/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1205066153005174/f
=> [Fix] bug in validations fields

example/themes/original/src/components/shared/OButton.tsx
STORY: https://app.asana.com/0/1198717964402573/1205225655001763
=> [Fix] button style issue

example/themes/kiosk/src/components/Checkout/index.tsx, example/themes/kiosk/src/components/CustomerName/index.tsx, example/themes/kiosk/src/components/PaymentOptions/index.tsx
story: https://app.asana.com/0/1199511033583011/1204451811414109/f
=> [Feat] get paymethods by device

example/themes/original/src/components/LoginForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1205277300312387/f
=> [Fix] hide apple login for android users

example/themes/original/src/components/Messages/index.tsx
story: https://app.asana.com/0/1199511033583011/1205259466310408/f
=> [Update] hide avatars in chat

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/Checkout/index.tsx, example/themes/original/src/components/ProductForm/ActionButton.tsx, example/themes/original/src/components/UpsellingProducts/UpsellingContent.tsx
story: https://app.asana.com/0/1199511033583011/1205327218246282/f
=> [Fix] default buttons color

example/themes/original/src/components/BusinessBasicInformation/index.tsx
Story: https://app.asana.com/0/1199511033583011/1205271159588666/f
Video: https://d.pr/v/K9Q9Pm
=> [FEAT] fix business category types

example/themes/business/src/components/UserProfileForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1205340463245146/f
=> [Fix] country code

example/themes/business/src/components/LogoutButton/index.tsx
story: https://app.asana.com/0/1199511033583011/1205235475469751/f
=> [Fix] languages issue

example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1205277300312387/f
=> [Fix] hide appel signup for android

example/themes/original/src/components/ProductForm/index.tsx, example/themes/original/src/components/ProductItemAccordion/index.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/UpsellingProducts/UpsellingLayout.tsx
Story: https://app.asana.com/0/1199511033583011/1205271159588662/f
Video: https://d.pr/v/pMPap3
=> [FEAT] dummy-logo-hide-theme

example/package.json
story: https://app.asana.com/0/1199511033583011/1205462037042187/f
=> [Fix] date picker version to avoid unstable last release

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/components/ProductOptionSubOption/index.tsx, example/themes/original/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1205446927744382/f
=> Autozoom map

example/themes/original/src/components/LoginForm/index.tsx, example/themes/original/src/components/SignupForm/index.tsx
story: https://app.asana.com/0/1199511033583011/1205451406320333/f
=> [Fix] prevent auto capitalize password

example/themes/original/src/components/MomentOption/index.tsx
Story: https://app.asana.com/0/1199511033583011/1205397016410065/f
=> [FEAT] fix-crash-ios

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/Home/index.tsx
story: https://app.asana.com/0/1199511033583011/1205482656696990/f
=> [Fix] unaddress redirect after sign up & as guest user

example/themes/original/src/components/BusinessPreorder/index.tsx
Story: https://app.asana.com/0/0/1205540794234319/f
=> [FEAT] fix crash ios calendar

example/package.json
story: https://app.asana.com/0/1199511033583011/1205446927744382/f
=> [Fix] google auto complete library new relase comes with a bug

example/themes/business/src/components/PreviousOrders/OrderItem.tsx
story: https://app.asana.com/0/0/1205577991340124/f
=> [Fix] visual issue in order item

example/themes/original/src/components/StripeElementsForm/naked.tsx
story: https://app.asana.com/0/1199511033583011/1205490937295943/f
=> [Fix] failed fetch because of token burned

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/GoogleMap/index.tsx, example/themes/original/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1205549515709621/f
=> [Update] prevent address input change when drag location

example/themes/original/src/components/AddressForm/index.tsx, example/themes/original/src/components/BusinessItemAccordion/index.tsx, example/themes/original/src/components/BusinessListingSearch/BusinessSearchFooter.tsx, example/themes/original/src/components/BusinessProductsList/SubcategoriesComponent/index.tsx, example/themes/original/src/components/BusinessProductsList/index.tsx, example/themes/original/src/components/BusinessTypeFilter/index.tsx, example/themes/original/src/components/BusinessesListing/Layout/Appointment/index.tsx, example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/CartContent/index.tsx, example/themes/original/src/components/ForgotPasswordForm/index.tsx, example/themes/original/src/components/MultiCheckout/index.tsx, example/themes/original/src/components/OrderDetails/index.tsx, example/themes/original/src/components/ProductForm/ActionButton.tsx, example/themes/original/src/components/SingleProductCard/index.tsx, example/themes/original/src/components/shared/OButton.tsx
story: https://app.asana.com/0/1199511033583011/1205453029326897/f
=> [Fix] fixes from buttons colors

example/themes/original/src/components/StripeCardsList/index.tsx
story: https://app.asana.com/0/1199511033583011/1205490937295943/f
=> [Fix] prevent to select more than 1 card

example/themes/business/src/utils/index.tsx
story: https://app.asana.com/0/1199511033583011/1205599744665225/f
=> [Fix] lang key for error

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx, example/themes/business/src/components/OrderDetails/Business.tsx, example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx, example/themes/business/src/components/OrderDetails/styles.tsx, example/themes/business/src/types/index.tsx
story: https://app.asana.com/0/1199511033583011/1205598560486797/f
=> [Fix] fixes and improvements for store app

example/themes/business/src/components/AcceptOrRejectOrder/index.tsx, example/themes/business/src/components/AcceptOrRejectOrder/styles.tsx, example/themes/business/src/components/OrderDetails/Business.tsx, example/themes/business/src/components/OrderDetails/OrderHeaderComponent.tsx
sotry: https://app.asana.com/0/1199511033583011/1205598560486797/f
=> [Fix] fixes & improvements

example/themes/original/src/components/OrderDetails/OrderEta.tsx
Story: https://app.asana.com/0/1199511033583011/1205643777775849/f
=> [FEAT] fix-preorder-delivery-time

example/themes/business/src/components/OrderDetails/OrderContentComponent.tsx, example/themes/business/src/components/OrderDetails/styles.tsx
story: https://app.asana.com/0/1199511033583011/1205598560486797/f
=> [Feat] add sport number in order detail

example/themes/original/src/components/OrderDetails/index.tsx
story: https://app.asana.com/0/1199511033583011/1205929150486792/f
=> [Fix] hide delivery fee on pickup

example/themes/original/src/components/UserVerification/index.tsx
=> Phone_Verification_Flag

example/themes/original/src/components/Checkout/index.tsx
Story: https://app.asana.com/0/1199511033583011/1206250044987367/f
=> [FEAT] commentDelayTime

example/themes/original/src/components/MomentSelector/index.tsx
Story: https://app.asana.com/0/0/1206259736793027/f
=> add-default-text-time-option

example/themes/original/src/components/OrderDetails/OrderHistory.tsx
Story: https://app.asana.com/0/1199511033583011/1206351585168283/f
=> [FEAT] fix-messages-shown-history-details

example/themes/business/src/components/BusinessProductList/index.tsx
Story: https://app.asana.com/0/1199511033583011/1206424005605472/f
=> [FEAT] fix no categories found

example/themes/original/src/components/UserFormDetails/index.tsx
Story: https://app.asana.com/0/1199511033583011/1206438078069732/f
Video: https://d.pr/v/Iml3Ab
=> [FEAT] fix-guest-user-checkout-info-details

example/themes/business/src/components/UserProfileForm/index.tsx, example/themes/business/src/components/UserProfileForm/styles.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/0/1206582940176687/f
=> [FEAT] add-remove-account

example/themes/original/src/components/PhoneInputNumber/index.tsx
Story: https://app.asana.com/0/0/1206602773985905/f
=> [FEAT] feedback-config-phone-validation

example/themes/original/src/components/ProductItemAccordion/index.tsx, example/themes/original/src/types/index.tsx
Story: https://app.asana.com/0/1199511033583011/1206331517969167/f
=> [FEAT] fix-sort-product-options

example/themes/original/src/components/ProductItemAccordion/index.tsx
Story: https://app.asana.com/0/0/1206975426018069/f
=> [FEAT] fix-sort-suboptions

example/themes/original/src/components/SignupForm/index.tsx
Story: https://app.asana.com/0/0/1207308892383290/f
=> [FEAT] fix-configs-validations

example/themes/original/src/components/Cart/index.tsx, example/themes/original/src/components/OrderSummary/index.tsx
Story: https://app.asana.com/0/1164464536714178/1207232490483415/f
=> [FEAT] fix-cart-comment-update

example/themes/original/src/components/LoginForm/index.tsx
Story: https://app.asana.com/0/1164464536714178/1207308892383290/f
=> [FEAT] fix-apple-login-enabled

example/themes/business/src/components/MapView/index.tsx, example/themes/business/src/types/index.tsx
Story: https://app.asana.com/0/1164464536714178/1207316341225010/f
=> [FEAT] fix-crash-delivery-app

example/themes/business/src/components/MapView/index.tsx
Story: https://app.asana.com/0/1164464536714178/1207489536989540/f
=> [FEAT] fix-mapa-not-showing

example/themes/business/src/components/OrdersOption/index.tsx
fix applied to internal release branch. fixing combine tabs default value state
=> fix: combineTabs state storage

example/themes/original/src/components/GoogleMap/index.tsx
Story: https://app.asana.com/0/1164464536714178/1209353762113514
=> fix: correct map toggle logic in GoogleMap component
